### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gasman1844** [signalkraft/mypyllant-component#10]
Installed myvaillant wihout any problems and working OK with aroTHERM plus heatpump + sensoCOMFORT VRC 720 + sensoNET VR 921. Very grateful, thank you.

My request is to have a control or service to set the duration of a temporary change made in the target temp. The default is 3 hours but the sensocomfort control allows one to increase that up to 12 hrs. The earlier HACS app sensoapp did this so hopefully it's possible.

**Comment by signalkraft** [comment]
That's lucky timing, I just released a version with more services. The one you're looking for is `set_quick_veto`. Let me know if it works for you, or if you see any errors.

**Comment by gasman1844** [comment]
Works fine. The combination of your integration with the new myvaillant app upgrade has made a huge difference to monitoring and running the heat pump. Thanks very much for your work on this.

**Comment by signalkraft** [comment]
Glad to hear that, thanks for the kind words!
