### ISSUE TITLE
Some consumption show empty but not show consumption fuel

### ISSUE THREAD

**Issue by pepsonEL** [signalkraft/mypyllant-component#106]
Hi. i Have boler EcoCompact VSC206 4-5 90 and now i see in your integration that for my boiler no show fule/gas consuption and all consuption is show for energy. But some show as 0 , and two show for heating( 48,125 Wh and 3100 Wh) but other  which show 0 is Domestic Hot Water. Someting is no good and no correct.

![image](https://github.com/signalkraft/mypyllant-component/assets/71824185/68c9967d-901c-4885-8598-df624e108a34)

```

**Comment by signalkraft** [comment]
Does the myVAILLANT app show the same thing, or does it look different?

**Comment by pepsonEL** [comment]
Yesterday in myVaillant app show that i must wait 48hours to collect data, but today this info is not show and show only temp power zone and pressure and show info about my boiler.

**Comment by pepsonEL** [comment]
and now in HA show more
![image](https://github.com/signalkraft/mypyllant-component/assets/71824185/8633da0f-41f5-4eaa-b4fd-a179dc2528b2)

**Comment by pepsonEL** [comment]
look
How my consuption look:
![image](https://github.com/signalkraft/mypyllant-component/assets/71824185/587c0870-dff0-4203-ae9c-6a65ad07262e)

![image](https://github.com/signalkraft/mypyllant-component/assets/71824185/380daa50-5f85-4a9d-a125-48b45fba0a77)

![image](https://github.com/signalkraft/mypyllant-component/assets/71824185/a17dd848-5ba6-4746-8999-de1f589a315b)


![image](https://github.com/signalkraft/mypyllant-component/assets/71824185/5a3364b6-ab08-4906-a69f-e67649f00fea)

**Comment by signalkraft** [comment]
Seems fine? These are daily totals that increase from 0 to whatever you use on that day. Add it to your energy dashboard, if you'd like to see totals over weeks or months.
