### ISSUE TITLE
Show heating operation in climate control like multimatic integration...

### ISSUE THREAD

**Issue by salzrat** [signalkraft/mypyllant-component#107]
### Before submitting a new issue

- [x] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [ ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

The Multimatic integration showed the area under the temperature curve in yellow when the heating was on. After migrating to myvaillant, in mypyllant I have to add the separate state entity to see when the heating was on, which takes up additional space. Can the climate control be extended to also show the heating state?

**Comment by signalkraft** [comment]
This is already part of the last few pre-releases, please try those.

**Comment by salzrat** [comment]
Thanks! I'm on 7.3b6, but don't see the heating in the climate control. Is there a newer one?

**Comment by salzrat** [comment]
maybe I wasn't clear. What I mean is that in the history graph card of the climate control, the heating state isn't visible. I've added it separately here, but in multimatic integration it was shown directly in the graph:

![image](https://github.com/signalkraft/mypyllant-component/assets/9115325/df34c410-0c15-4f8a-8381-be1ee13b23dc)

**Comment by signalkraft** [comment]
There's two newer releases, both should have the heating state in the graph.

**Comment by salzrat** [comment]
after b8, it still looks like above - or is the heating state in the graph only available from installation of the update onward?

**Comment by salzrat** [comment]
Ok, now it seems to work, thanks!
