### ISSUE TITLE
No gas consumption

### ISSUE THREAD

**Issue by ZaphodB72** [signalkraft/mypyllant-component#110]
Before this integration I used the MultiMATIC Integration, which showed Gas consumption for heating and hot water.
These entities are empty in this myVAILLANT-Imtegration but are still shown in the myVAILLANT-App.
I‘m using Vaillant ecotherm with VRC900

**Comment by Gio-dot** [comment]
It is working here.. 
![Screenshot_20240221_003806_Home Assistant](https://github.com/signalkraft/mypyllant-component/assets/55327160/263d1607-eeaf-423c-a756-32cdf4472f81)

**Comment by signalkraft** [comment]
@ZaphodB72 has it started working for you?

**Comment by ZaphodB72** [comment]
Yes, it’s working now! Thank you!
