### ISSUE TITLE
Entity None (<class 'custom_components.mypyllant.climate.ZoneClimate'>) implements HVACMode(s): heat_cool, off, auto

### ISSUE THREAD

**Issue by ThomasBergholdWieser** [signalkraft/mypyllant-component#112]
Problem:
I have not seen any issues regarding functionality, however:

The log states the following: 
Entity None (<class 'custom_components.mypyllant.climate.ZoneClimate'>) implements HVACMode(s): heat_cool, off, auto and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/signalkraft/mypyllant-component/issues

**Comment by signalkraft** [comment]
Fixed in the latest pre-release, thanks for the info.
