### ISSUE TITLE
Configuration page / Check Boxes

### ISSUE THREAD

**Issue by mike4001** [signalkraft/mypyllant-component#115]
### Before submitting a new issue

- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [ ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

I wanted to check the box that temperatur changes will not apply to Quick Veto but to the normal temperature.

but the configuration page looks like this

![image](https://github.com/signalkraft/mypyllant-component/assets/26521177/0aa474e3-96f8-4fe2-8f6c-b823c4717cff)

If I check the top checkbox I get

![image](https://github.com/signalkraft/mypyllant-component/assets/26521177/e2c4648a-b604-43b7-b07c-48fe6cafa806)

### Logs

```
Put your debug logs here
Be careful not to include tokens, emails, and other personal information
```

**Comment by fodorg01** [comment]
I can confirm this problem, it is the same for me.

**Comment by signalkraft** [comment]
https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.4b6 should fix this problem

**Comment by mike4001** [comment]
Thank you.

Can confirm this is fixed
