### ISSUE TITLE
Delay in receiving update from server

### ISSUE THREAD

**Issue by gasman1844** [signalkraft/mypyllant-component#12]
Have arotherm plus and myvaillant app with sensoCOMFORT VRC 720 + sensoNET VR 921 based in UK.
Two day history of one-way delay from server to HA. Sending commands to the server work OK. So for example I send a command for a quick mode change of temp, the change in target temp shows in the mobile myvaillant app but the target temp sensor in HA doesn't update for about half an hour.
I have reloaded and also reinstalled app. I have looked at the logs and there doesn't appear to be any obvious problem, it's just that the update to the new value is delayed. I can upload debug data if that would be helpful.
I delayed reporting in case it was a server issue. But the myvaillant app updates normally while the HA data is delayed.

**Comment by signalkraft** [comment]
I commented in #13, will close this one.

**Comment by gasman1844** [comment]
Feedback after 3 days - the new beta works well - in fact it updates in a matter of seconds, faster than the android vaillant app.
Much appreciated. I was starting to think I would have to wire in an ebusd interface but your new component works so well I don't think I will need it. If you want to add a 'buy me a coffee' button to your repository, I'm happy to make a contribution.
