### ISSUE TITLE
Climate entity gone?

### ISSUE THREAD

**Issue by minosrex** [signalkraft/mypyllant-component#124]
Today I downloaded and installed the latest version, after running into [this](https://github.com/signalkraft/mypyllant-component/issues/116) issue.

Good news: not only did the entities come back, I know have some very useful info such as the present heating curve.

Bad news: the climate entity is gone. Anyone else has this issue?

**Comment by fhbonte** [comment]
Hallo, same here, as from v0.7.4 climate enity are not available anymore (ecoTEC exclusive, VR920 with multimatic VRC700)

**Comment by signalkraft** [comment]
[Please create a bug report](https://github.com/signalkraft/mypyllant-component/issues/new/choose), I can't help you without more details.

**Comment by minosrex** [comment]
Bug report created with the logs. Thanks!
