### ISSUE TITLE
Vaillant Device 0 ecoTEC plus > Status unavailable

### ISSUE THREAD

**Issue by PV-Joe** [signalkraft/mypyllant-component#133]
I updated the Vaillant iOS App and installed  myVaillant.

Since about two days the Device 0 sensors are unavailable:

![IMG_5106](https://github.com/signalkraft/mypyllant-component/assets/110498562/7302bf52-b4a0-48b7-9a1d-63e1b1389f0e)

Is there anything I can do about it or ist the API causing the problem?

Big thx for the nice integration!

P.S.: Reloading and restart did not help.

**Comment by Gizmo0815** [comment]
My integration stoped providing energy consumption data tonight at 0:47:08 aswell.
![grafik](https://github.com/signalkraft/mypyllant-component/assets/16947043/429d7781-9b3f-4868-b85b-98da8f8cc626)

**Comment by PV-Joe** [comment]
I hope it will come back as I used the Vaillant sensors in my Energy Dashboard and it was working fine for two days.

There is no option to view those values in the official iOS myVAILLANT App either.

Glad that I‘m not the only one suffering.
Thx for replying.

**Comment by Acey-yo** [comment]
Hello, I've been getting all the data normally again for a short time. I think it's really because of the Vaillanz cloud.

**Comment by thopfei** [comment]
Energy data delivery is now back to normal. 
Vaillant is preparing the next release of the myVAILLANT app and will then support ambisense thermostate.

**Comment by PV-Joe** [comment]
> Energy data delivery is now back to normal. Vaillant is preparing the next release of the myVAILLANT app and will then support ambisense thermostate.

Here as well. The Vaillant sensors are working again 👍
