### ISSUE TITLE
Consumed Electrical or Primary for Hot Water or Heating is Unknown (4 Entities)

### ISSUE THREAD

**Issue by Torsten-Fischer** [signalkraft/mypyllant-component#134]
### Before submitting a new issue

- [ yes] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [ yes] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [ yes] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

After today's update (March 12, 2024) I noticed that the energy consumed is no longer displayed.
The entities:
- sensor.home_device_0_vc_20cs_1_5_n_de_ecotec_plus_consumed_electrical_energy_domestic_hot_water
- sensor.home_device_0_vc_20cs_1_5_n_de_ecotec_plus_consumed_electrical_energy_heating
- sensor.home_device_0_vc_20cs_1_5_n_de_ecotec_plus_consumed_primary_energy_domestic_hot_water
- sensor.home_device_0_vc_20cs_1_5_n_de_ecotec_plus_consumed_primary_energy_heating
have the status unknown.
For example, I had entered the primary_energy entities in the energy dashboard for gas consumption.
I use a Vaillant VC 20CS/1-5 (N-DE) ecoTEC plus with VR921.

**Comment by Acey-yo** [comment]
Hello, 

i have the same problem since 2 days. Yesterday, after a restart, it was back, but no data arrived. Now I restarted again and now no more data arrives.

**Comment by mathisschmieder** [comment]
I think this might be an issue/"update?" at Vaillant, and not specific to this integration. I also noticed that the information was missing starting March 11th, and the myVaillant app also shows no consumed power information for the *current* day. Today, yesterday's values suddenly appeared.

**Comment by PV-Joe** [comment]
This issue describes the same behavior:

https://github.com/signalkraft/mypyllant-component/issues/133

It’s probably better to merge them.

**Comment by Torsten-Fischer** [comment]
I will close the issue.
The data is available again today without me having done anything.
