### ISSUE TITLE
Power vs Energy - Update/fix and additional sensor request

### ISSUE THREAD

**Issue by BergenLarsen** [signalkraft/mypyllant-component#14]
Hi!

Firstly - thanks for getting this sorted and integrated! 

I've got a few things I'd like to request changed and another request for an additional sensors on the integration and it's all related to the power sensors - or what you've labelled as energy. I'm happy to offer assistance - although I'd not consider myself a coder/developer - but more of a person who can tinker to get code working sometimes. 😅 

Specifically these:

Entity | Unit | Class | Sample
-- | -- | -- | --
aroTHERM plus Consumed Electrical Energy Heating | Wh | energy | 0
aroTHERM plus Earned Environment Energy Domestic Hot Water | Wh | energy | 0
aroTHERM plus Earned Environment Energy Heating | Wh | energy | 334.5
aroTHERM plus Heat Generated Heating | Wh | energy | 334.5
aroTHERM plus Heat Generated Domestic Hot Water | Wh | energy | 3

I specifically left out this sensor: "Hydraulic Station Consumed Electrical Energy Domestic Hot Water" as I don't have it and I can't see the data it's generating. 

The way the data reads is that this is power (current consumption/creation) measured in watts, rather than energy (power over time) measured as watt hours. The HA team explain a it more in depth here:  https://www.home-assistant.io/docs/energy/faq/

As way of example, here's a sensor with Energy data:
![image](https://user-images.githubusercontent.com/47712770/235961694-1eb0e905-a929-4aeb-b820-26a1b50534c5.png)
Here's a sensor with Power data:
![image](https://user-images.githubusercontent.com/47712770/235961826-f2edf541-09ca-4a0d-9e6c-03ae3ad24f02.png)

.. so based on the above, the sensor for the Vaillant is showing up like power, but is labelled as energy which throws off all kinds of dashboards for me in home assistant. 😨 

![image](https://user-images.githubusercontent.com/47712770/235961348-a1f766c7-7f59-4c21-94b1-d5aab002f5c8.png)

So first the change (fix?) I'd like to request which should be simple enough:

Entity | Unit | Class | Sample | Comment
-- | -- | -- | -- | --
aroTHERM plus Current Power for Heating | W | power | 0 | Label change and unit change
aroTHERM plus Captured Environmental Heat for Domestic Hot Water | W | power | 0 | Label change and unit change
aroTHERM plus Captured Environmental Heat for Heating | W | energy | 334.5 | Label change and unit change
aroTHERM plus Current Heat Generation Heating | W | energy | 334.5 | Label change and unit change
aroTHERM plus Current Heat Generation Domestic Hot Water | W | energy | 150 | Label change and unit change

Then as a further request, create some sensors that give energy.
So similar to the above, but with two additional attributes:
state_class and last_reset

https://developers.home-assistant.io/docs/core/entity/sensor/#entities-representing-a-total-amount

Entity | Unit | Class | Sample | Comment
-- | -- | -- | -- | --
aroTHERM plus Energy consumed for Heating Today | Wh | power | 2450 | new sensor entity with state_class: total_increasing & last_reset at Midnight
aroTHERM plus Environmental Energy Captured for Domestic Hot Water Today | Wh | power | 2580 | new sensor entity with state_class: total_increasing & last_reset at Midnight
aroTHERM plus Environmental Energy Captured for Heating Today | Wh | energy | 334.5 | new sensor entity with state_class: total_increasing & last_reset at Midnight
aroTHERM plus Total Heat Generated for Heating Today | Wh | energy | 334.5 | new sensor entity with state_class: total_increasing & last_reset at Midnight
aroTHERM plus Total Heat Generated for Domestic Hot Water Today | Wh | energy | 150 | new sensor entity with state_class: total_increasing & last_reset at Midnight

Let me know if you'd like me to help tweak this with you or if I'm on my own!
- Bergen

**Comment by signalkraft** [comment]
Hey, thanks for the thorough report, and sorry it took me a while to respond.

I got to the current state of these entities by just mapping the names of the values from the Vaillant API to the corresponding units in HA. Vaillant calls it energy, so I assumed it's energy: https://github.com/signalkraft/mypyllant-component/blob/main/custom_components/mypyllant/sensor.py#L32

As far as I can tell from the myVAILLANT app, there are no power values in their API. It's all Wh, or energy. And it's not `total_increasing` energy data, like in your first screenshot. Rather, it reports how much energy was used in each time period (you can pick between hourly and daily).

From reading HA's documentation, I can't figure out how I can cleanly map that to HA values. The best I could come up with was this:

* Schedule a hourly read
* Get all hourly values from the API, grab the latest value and it's time period (let's say 8-9am)
* Save that value with `last_reset` at the start of the period (so 8am)
* Wait for HA to schedule the next read one hour later, hope the sun & moon line up and we end up reading the next hourly bucket. Maybe the scheduler takes a bit longer and we miss a window? Maybe we read sth twice? Does it matter if we set `last_reset`? I don't know, the custom component sensor docs in HA are short and confusing, and no other 3rd party component seems to report its data like Vaillant, so I procrastinate this ticket for 3 months and secretly hope that Vaillant refactors this part of their API, just like they refactored every other part 3 times already

Of course, I could also just read this data daily. But where's the fun in that?

--

If you have any ideas how I could translate the data I get from Vaillant into HA more cleanly and more robustly, I'm happy to implement it.

**Comment by signalkraft** [comment]
I found an acceptable middleground: I'm getting the daily readings and changed the sensor to total_increasing. The values seem less precise, but at least there's no more delay and no more mismatch between the data and what HA expects.

**Comment by BergenLarsen** [comment]
Hey! Apologies for the tardy reply. I see you updated the component - I've not done the thorough investigation, but I did notice things changing.  (Also - separate ticket - but water pressure disappeared?)

It seems like there were updates, and it seems to make sense now - well the data that's showing in the graphs.  

So from what you've described, possibly what was missing was the total increasing and last updated flag?   Did they also end up updating the api?
