### ISSUE TITLE
aroTHERM plus On/Off Cycles

### ISSUE THREAD

**Issue by froggi1930** [signalkraft/mypyllant-component#143]
Hi there,

I have updated to the latest version and the "aroTHERM plus On/Off Cycles" is no longer available.

Will it come back?

Kind regards,

Georg

**Comment by signalkraft** [comment]
Please enable the RTS & MPC options in the configuration of the integration, they're off by default because a lot of users got 404 errors all the time.

**Comment by froggi1930** [comment]
Where do I find those settings?
![image](https://github.com/signalkraft/mypyllant-component/assets/76737803/7b04853a-b97e-45ce-ac9a-e588ee7ec7eb)

**Comment by camhef** [comment]
The last two tick boxes on you screenshot enable these options. So it should work for you. You may need to reload the integration before the data is visible.
