### ISSUE TITLE
Consumed Electrical or energy not working anymore

### ISSUE THREAD

**Issue by pinkfloydFR** [signalkraft/mypyllant-component#16]
Hi,

Since one week, energy are not working anymore : 

![image](https://github.com/signalkraft/mypyllant-component/assets/49475899/6b5974c6-34a6-417e-afdd-5b4a15cbfa46)

Still  in v0.2.0 version, using sensoCOMFORT ( rebooted as well )

On the phone app, still have the data.

NB, don't know if it's important, but i think the problem appear when i switched heater off.

Thanks for this integration btw.

.
.

EDIT : **Tested with v0.3.0** : 

Energy always unavailable, BUT : 

**Water Pressure ecoTEC** seem to be replaced by : **System Water Pressure**
**System Mode** seem to be replaced by : **Current Special Function Domestic Hot Water 255**
**Min Flow Temperature Setpoint in Circuit 0** seem to have no replacement

two new sensor : 
![image](https://github.com/signalkraft/mypyllant-component/assets/49475899/f9538b56-1a20-4861-b552-3a4719705ebe)

**Comment by erikvtv** [comment]
I’m also have same problem.

attached some logging , maybe helpful

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.mypyllant
Source: custom_components/mypyllant/__init__.py:165 
Integration: myVAILLANT (documentation, issues) 
First occurred: 10 mei 2023 om 13:43:42 (3 occurrences) 
Last logged: 19:23:02

Unexpected error fetching myVAILLANT data: 14 validation errors for DeviceData data -> 11 -> value field required (type=value_error.missing) data -> 12 -> value field required (type=value_error.missing) data -> 13 -> value field required (type=value_error.missing) data -> 14 -> value field required (type=value_error.missing) data -> 15 -> value field required (type=value_error.missing) data -> 16 -> value field required (type=value_error.missing) data -> 17 -> value field required (type=value_error.missing) data -> 18 -> value field required (type=value_error.missing) data -> 19 -> value field required (type=value_error.missing) data -> 20 -> value field required (type=value_error.missing) data -> 21 -> value field required (type=value_error.missing) data -> 22 -> value field required (type=value_error.missing) data -> 23 -> value field required (type=value_error.missing) data -> 24 -> value field required (type=value_error.missing)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/mypyllant/__init__.py", line 165, in _async_update_data
    data.append([da async for da in device_data])
  File "/config/custom_components/mypyllant/__init__.py", line 165, in <listcomp>
    data.append([da async for da in device_data])
  File "/usr/local/lib/python3.10/site-packages/myPyllant/api.py", line 281, in get_data_by_device
    yield DeviceData(
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 259, in __init__
    super().__init__(device=device, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 14 validation errors for DeviceData
data -> 11 -> value
  field required (type=value_error.missing)
data -> 12 -> value
  field required (type=value_error.missing)
data -> 13 -> value
  field required (type=value_error.missing)
data -> 14 -> value
  field required (type=value_error.missing)
data -> 15 -> value
  field required (type=value_error.missing)
data -> 16 -> value
  field required (type=value_error.missing)
data -> 17 -> value
  field required (type=value_error.missing)
data -> 18 -> value
  field required (type=value_error.missing)
data -> 19 -> value
  field required (type=value_error.missing)
data -> 20 -> value
  field required (type=value_error.missing)
data -> 21 -> value
  field required (type=value_error.missing)
data -> 22 -> value
  field required (type=value_error.missing)
data -> 23 -> value
  field required (type=value_error.missing)
data -> 24 -> value
  field required (type=value_error.missing)

**Comment by ardyp87** [comment]
Having same issue.

**Comment by chrizzzp** [comment]
Thanks for the efforts on this integration! 
Was forced to migrate to MyVaillant (from SensoApp/Multimatic integration). Vaillant continously pushes users to the new system, so I guess more and more people will look into the mypyllant-component...

My system: Vaillant arotherm Split heatpump (+ hydraulic station) + sensoCOMFORT VRC 720 + sensoNET VR 921
mypyllant-component: latest pre-release of  v0.3.0b0

I do see 16 entities from the integration in HA, but none of them refers to energy/power consumption (except [sensor.heating_energy_efficiency]).

Should I try v0.2?
Turned debugging on. What debugging info should be posted?

Thanks again!

**Comment by on5bac** [comment]
> Hi,
> 
> Since one week, energy are not working anymore :
> 
> ![image](https://user-images.githubusercontent.com/49475899/238122423-6b5974c6-34a6-417e-afdd-5b4a15cbfa46.png)
> 
> Still in v0.2.0 version, using sensoCOMFORT ( rebooted as well )
> 
> On the phone app, still have the data.
> 
> NB, don't know if it's important, but i think the problem appear when i switched heater off.
> 
> Thanks for this integration btw.
> 
> . .
> 
> EDIT : **Tested with v0.3.0** :
> 
> Energy always unavailable, BUT :
> 
> **Water Pressure ecoTEC** seem to be replaced by : **System Water Pressure** **System Mode** seem to be replaced by : **Current Special Function Domestic Hot Water 255** **Min Flow Temperature Setpoint in Circuit 0** seem to have no replacement
> 
> two new sensor : ![image](https://user-images.githubusercontent.com/49475899/238123323-f9538b56-1a20-4861-b552-3a4719705ebe.png)


We have exactly the same problem here and I can confirm that it started from the moment that we switched off the heater for the CV part. In the MyVaillant app it is still visible.

**Comment by chrizzzp** [comment]
> I do see 16 entities from the integration in HA, but none of them refers to energy/power consumption (except [sensor.heating_energy_efficiency]).
> 
> Should I try v0.2?

I can confirm in version 0.2 energy/power consumption entities don't work anymore either (also not in 0.3beta). I assume there were API changes?

**Comment by signalkraft** [comment]
I released a new beta version v0.3.0b1 that may fix this, let me know if it works.

Vaillant indeed changed the API, I'm not sure if some users are still on the API that version 0.2.x was built for.

**Comment by pinkfloydFR** [comment]
Hi, thanks for the new release seems to be good for consumsion 👍 

![image](https://github.com/signalkraft/mypyllant-component/assets/49475899/987de397-5410-4c0e-895b-3a8b17c7d95d)


juste this sensor always ko : 

![image](https://github.com/signalkraft/mypyllant-component/assets/49475899/3862a31d-f98b-41b3-8032-f342be5cf7e5)


But thanks for the great work anyway !

**Comment by erikvtv** [comment]
It’s working with v0.3.0b2. Thank you for your effort to fix the issue

**Comment by didierhassio** [comment]
Bonjour,
Les consommations refonctionnent chez moi aussi avec la v0.3.0b1 et une saunier duval DUOMax.
Merci pour la mise à jour,

**Comment by andreaconsadori** [comment]
On therma condens still unknown After 4 hours

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by andreaconsadori** [comment]
Start Reading new value After 24hours

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
