### ISSUE TITLE
flexoTherm exclusive + VR920 Lack of Support for Cooling/Air Conditioning

### ISSUE THREAD

**Issue by prezesBB** [signalkraft/mypyllant-component#164]
I am experiencing a lack of support for the cooling function integration with my heat pump. When I activate cooling in the myVaillant app, Home Assistant displays the status as "off."

**Comment by signalkraft** [comment]
This should be improved in newer versions. If it doesn't, please open a new issue and fill out the whole template, so I'm able to help you.
