### ISSUE TITLE
Activating away mode not working

### ISSUE THREAD

**Issue by flobo1990** [signalkraft/mypyllant-component#17]
Hello,
It does not seem to be possible to activate the away mode. No error message, but nothing happens.
![image](https://github.com/signalkraft/mypyllant-component/assets/61708287/3a355a73-7b07-4980-ac79-84afd82ab4ce)

Deactivating the away mode after activating it via app, on the other hand, works without problems.

**Comment by signalkraft** [comment]
How about using this:

```service: mypyllant.set_holiday
data: {}
target:
  entity_id: climate.zone_0
```

For me, this works from the developer tools. The built-in "set preset" doesn't work, however when using the UI in Home Assitant (the dropdown to set the preset mode in the default UI for a climate entity), away mode gets activated in my case.

**Comment by boelle** [comment]
@flobo1990 ??

**Comment by flobo1990** [comment]
Sorry, yes that works. Thanks
