### ISSUE TITLE
Login into Vailant account in 2024.06.0 does not work

### ISSUE THREAD

**Issue by matejsalamon** [signalkraft/mypyllant-component#170]
### Before submitting a new issue

- [ ] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [ ] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [ ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Please describe what you were trying to do, what happened, and what you expected to happen.

### Logs

```
Put your debug logs here
Be careful not to include tokens, emails, and other personal information
```

**Comment by matejsalamon** [comment]
Since update to 2024.06.0 there is no way to login into Vailant account in the HA. In myVailant app login works normal. Here is the HA log in this case:

This error originated from a custom integration.

Logger: custom_components.mypyllant.config_flow
Source: custom_components/mypyllant/config_flow.py:225
integration: myVAILLANT (documentation, issues)
First occurred: 10:08:58 AM (3 occurrences)
Last logged: 10:10:33 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mypyllant/config_flow.py", line 225, in async_step_user
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2258, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured

**Comment by BenE-O** [comment]
Same with me!
The last update enables download
When using the wrong password, I receive the message: Authentication failed, check your username and password and make sure you selected the right country and device brand
But logging in with the correct credentials generates the following message: unexpected error

**Comment by lieglw** [comment]
Hi, had the same problem. I had deactivated the entry and somehow HA saved it even though I deleted the integration several times and reinstalled ist. When checking the integration overview I have seen that there was a deactivated integration. So activated again and now it works. Did not had to reenter the credentials.

**Comment by BenE-O** [comment]
You're right, this solved my problem. I had to remove and reinstall, because I changed my password :-)
Thanks!
