### ISSUE TITLE
Wrong version nummber in Integration page

### ISSUE THREAD

**Issue by JavanXD** [signalkraft/mypyllant-component#178]
In the HACS store this is the version number:
<img width="244" alt="image" src="https://github.com/signalkraft/mypyllant-component/assets/4342160/6b09c713-376e-405e-b3af-70a838dd0cfb">

But if you click on "Add Integration", this is the version number displayed: 
<img width="320" alt="image" src="https://github.com/signalkraft/mypyllant-component/assets/4342160/a9cd28c9-1024-4e67-80f7-566acab47e81">

**Comment by JavanXD** [comment]
bug is here: https://github.com/signalkraft/mypyllant-component/blob/14e0339ecbdcaad1a5c8a2bfc0b68187793b4135/custom_components/mypyllant/manifest.json#L15

**Comment by JavanXD** [comment]
Duplicate of https://github.com/signalkraft/mypyllant-component/issues/166

**Comment by signalkraft** [comment]
Should work in the latest release https://github.com/signalkraft/mypyllant-component/releases/tag/v0.8.4
