### ISSUE TITLE
Integration stops working when Cooling Mode is active 

### ISSUE THREAD

**Issue by CommanderROR9** [signalkraft/mypyllant-component#18]
Hi,
Today my Arotherm Plus went into cooling mode and soon after it did all entities for this myVaillant integration completely stopped responding.

After I returned it to heating mode it started working again.

I did not capture any logs unfortunately, but id it happens again I can do so.
I am running 0.2 since the 0.3 beta didn't work for me.

**Comment by Panzke** [comment]
I can confirm this. All entities are gone for me. 

I use the beta v0.3.0b0.

**Comment by antonclaeys** [comment]
i can confirm as well.
Arotherm split WVL 75

**Comment by chheiss** [comment]
Same here!

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.mypyllant
Source: custom_components/mypyllant/__init__.py:140 
Integration: myVAILLANT (documentation, issues) 
First occurred: 11:29:10 (1 occurrences) 
Last logged: 11:29:10

Unexpected error fetching myVAILLANT data: 1 validation error for Zone heating_state value is not a valid enumeration member; permitted: 'IDLE', 'HEATING_UP' (type=type_error.enum; enum_values=[<ZoneHeatingState.IDLE: 'IDLE'>, <ZoneHeatingState.HEATING_UP: 'HEATING_UP'>])
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/__init__.py", line 140, in _async_update_data
    data = [
           ^
  File "/config/custom_components/mypyllant/__init__.py", line 140, in <listcomp>
    data = [
           ^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 256, in get_systems
    system = System(
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 158, in __init__
    self.zones = [Zone(system_id=self.id, **z) for z in self._merged_zones]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 158, in <listcomp>
    self.zones = [Zone(system_id=self.id, **z) for z in self._merged_zones]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 108, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Zone
heating_state
  value is not a valid enumeration member; permitted: 'IDLE', 'HEATING_UP' (type=type_error.enum; enum_values=[<ZoneHeatingState.IDLE: 'IDLE'>, <ZoneHeatingState.HEATING_UP: 'HEATING_UP'>])

**Comment by antonioal1970** [comment]
i can confirm as well.

**Comment by 06bka01** [comment]
So do I, confirmed

**Comment by signalkraft** [comment]
Sorry for the long wait, this should work on v0.3.0b1 now.
