### ISSUE TITLE
version number

### ISSUE THREAD

**Issue by boelle** [signalkraft/mypyllant-component#183]
not sure if or where the problem is

the phone app works fine, but on home assistant i get nothing

vaillant in Denmark out of the blue decided i needed a new box while the old one was working fine both in app an in HA

![image](https://github.com/signalkraft/mypyllant-component/assets/3832239/7c3f372e-5137-41a1-adf2-ca44a4a40f9f)

PS, even thou i have updated to the latest beta it still shows an old version number

@signalkraft

**Comment by boelle** [comment]
seeems i just had to wait a lot longer for things to show up

just as i had to do in the app, in fact for the app i had to wait about 8 hours (while sleeping...)

in HA maybe 10 minutes

the version issue is still there thou

**Comment by signalkraft** [comment]
Should work in the latest release https://github.com/signalkraft/mypyllant-component/releases/tag/v0.8.4
