### ISSUE TITLE
Incorrect setpoint temperature in ECO mode

### ISSUE THREAD

**Issue by didierhassio** [signalkraft/mypyllant-component#185]
Hello
I'm using the latest version of Myvaillant.
When the outside temperature passes a threshold set in the thermostat (TE cut-off threshold), the heating is switched off, the set temperature drops to zero and the ECO mode is displayed on the display.
Using Services and mypyllant.generate_test_data development tools, I can see the set temperature going to zero.
desiredRoomTemperatureSetpointHeating: 0
desiredRoomTemperatureSetpoint: 0
But the "sensor.my_home_zone_1_circuit_0_desired_temperature" sensor is at 18°.
If I turn off the heating "sensor.my_home_zone_1_circuit_0_desired_temperature" goes to 0°
I am attaching the 3 files for analysis.
Thank you
[Mode ECO.txt](https://github.com/user-attachments/files/16082959/Mode.ECO.txt)
[Mode normal.txt](https://github.com/user-attachments/files/16082960/Mode.normal.txt)
[Mode OFF.txt](https://github.com/user-attachments/files/16082961/Mode.OFF.txt)
![Screenshot_2024-05-16-11-08-30-20_6b53f0dc5cbd7a58da62b9cf6081846f](https://github.com/signalkraft/mypyllant-component/assets/60665275/a887d6c0-dc8e-49fd-b027-e3e9cc4d9726)

**Comment by signalkraft** [comment]
Just to be clear: You would expect desired temperature to be 0, right? It's currently set to `set_back_temperature` when it's in Eco mode. The logic being, that the heating system would not let the temperature drop below that. But I might be off on that.

**Comment by didierhassio** [comment]
Yes, I would like "sensor.my_home_zone_1_circuit_0_desired_temperature" to display its true value (0) as below:
          desiredRoomTemperatureSetpointHeating: 0
          desiredRoomTemperatureSetpoint: 0

**Comment by didierhassio** [comment]
I just installed the v08.11 version and the climate appears at 0°, but the "sensor.my_home_zone_1_circuit_0_desired_temperature" sensor remains at 18°, can you correct it so that it is also at 0°?
Thank you again for the speed and the work done.

**Comment by didierhassio** [comment]
I just installed version v08.12 and the ECO mode works perfectly.
Thank you again for the speed and the work done.
