### ISSUE TITLE
Change in how energy values are rounded?

### ISSUE THREAD

**Issue by dylan09** [signalkraft/mypyllant-component#191]
### Before submitting a new issue

- [X] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [X] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [ ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description
After the update to the latest version a few days ago all energy sensors are rounded to multiple of hundreds. Before the update I get readings e.g. 4621,02 Wh. Since than all energy sensors show values round to hundreds e.g. 4600,0 Wh.

Is this a change in the integration or in the Valiant cloud? Or is there something that I have mistakenly changed in my heating system?

**Comment by signalkraft** [comment]
It's a change in the integration in an attempt to fix https://github.com/signalkraft/mypyllant-component/issues/157

**Comment by dylan09** [comment]
Oh. Its OK. Only a question if I have observed it correct. And if it is a change due to be in line with the Vaillant app ist also fine for me 😉
