### ISSUE TITLE
Combination Ecotec exclusive vc245 with VR920 doesn't seem to work

### ISSUE THREAD

**Issue by Kal0305** [signalkraft/mypyllant-component#192]
### Before submitting a new issue

- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Please describe what you were trying to do, what happened, and what you expected to happen.
When I set account, password etc., after acknowledging, I expect the integration to connect to the VR920 or cloud. However, it keeps saying "no apparatus or entity" under Hubs in myVAILLANT.

### Logs
first error log:
Logger: homeassistant.util.loop
Bron: util/loop.py:136
Eerst voorgekomen: 21:11:28 (1 gebeurtenissen)
Laatst gelogd: 21:11:28

Detected blocking call to listdir with args ('/config/deps/lib/python3.12/site-packages',) inside the event loop by custom integration 'mypyllant' at custom_components/mypyllant/__init__.py, line 90: version("myPyllant"), (offender: /usr/local/lib/python3.12/importlib/metadata/__init__.py, line 680: return os.listdir(self.root or '.')), please create a bug report at https://github.com/signalkraft/mypyllant-component/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 451, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 734, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/mypyllant/__init__.py", line 90, in async_setup_entry version("myPyllant"),

Second error log:
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.mypyllant.coordinator
Bron: helpers/update_coordinator.py:312
integratie: myVAILLANT (documentatie, problemen)
Eerst voorgekomen: 21:11:31 (2 gebeurtenissen)
Laatst gelogd: 21:11:33

Unexpected error fetching myVAILLANT data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/coordinator.py", line 177, in _async_update_data
    data = [
           ^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 360, in get_systems
    system = System.from_api(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 950, in from_api
    DomesticHotWater.from_api(
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 573, in from_api
    data["current_special_function"] = DHWCurrentSpecialFunctionVRC700(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'BANK_HOLIDAY' is not a valid DHWCurrentSpecialFunctionVRC700

```
Put your debug logs here
Be careful not to include tokens, emails, and other personal information
```

**Comment by Kal0305** [comment]
The strange thing is, that with this (calling myVAILLANT: Generate Test Data):
![image](https://github.com/user-attachments/assets/da9106ab-fa7e-4528-934d-c9d9188d96f4)
I do get the right data from this instance. Temperature, humidity etc. correspond the current system status.

**Comment by signalkraft** [comment]
This should work in the latest release.
