### ISSUE TITLE
Turning on hot water doesn’t work

### ISSUE THREAD

**Issue by dhoerpel** [signalkraft/mypyllant-component#195]
Hi there,

My setup:

Vaillant 105/5 AS S2
Vaillant VWL 127/5 IS
Vaillant sensoNET VR 921

When trying to turn on my hot water, HA displays the correct sensor values but if I'm trying to change the current mode by any automation / manually, the action is being executed without any error handling but the new value is not taken into consideration.
Available values:
- Auto
- Day
- Off

It would be great if the value auto could be set for an automated scheduling of the hot water cycle.

When trying to turn off my hot water (value off), I do not experience any issues.

**Comment by signalkraft** [comment]
Please create a new ticket and fill out the bug template, I can't help you without logs.
