### ISSUE TITLE
Request - support for Bolier

### ISSUE THREAD

**Issue by joselaya** [signalkraft/mypyllant-component#2]
Hi there, 

I'm looking for something similar for my Vaillant Vaillant Ecotec Plus 32 (boiler) + sensoHOME VRT 380f + sensoNET

I have tried with my app account and I can log in correctly, but it does not show any device. 

Do you think I can use this for the installation I have at home? 

Thanks in advance 👍

**Comment by signalkraft** [comment]
Are you using the myVAILLANT app for your setup? If yes, you could try turning on debug logging for this integration, refreshing it, and posting the results here.

**Comment by joselaya** [comment]
Yes, I use the myVAILLANT app. 
I think I'm doing something wrong or I'm missing something to configure :-(
Thanks for your help!

2023-02-28 16:25:35.905 ERROR (MainThread) [custom_components.mypyllant] Unexpected error fetching myVAILLANT data: 2 validation errors for Circuit
heating_curve
  field required (type=value_error.missing)
min_flow_temperature_setpoint
  field required (type=value_error.missing)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/mypyllant/__init__.py", line 129, in _async_update_data
    data = [
  File "/config/custom_components/mypyllant/__init__.py", line 129, in <listcomp>
    data = [
  File "/usr/local/lib/python3.10/site-packages/myPyllant/api.py", line 198, in get_systems
    system = System(
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 115, in __init__
    self.circuits = [Circuit(system_id=self.id, **c) for c in self._raw_circuits]
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 115, in <listcomp>
    self.circuits = [Circuit(system_id=self.id, **c) for c in self._raw_circuits]
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 342, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for Circuit
heating_curve
  field required (type=value_error.missing)
min_flow_temperature_setpoint
  field required (type=value_error.missing)

**Comment by signalkraft** [comment]
@joselaya could you try again with version v0.0.19? Thanks to https://github.com/signalkraft/myPyllant/pull/3 the missing fields are now optional.

This sort of problem may pop up a few more times while you're setting up this component, because I had no way of testing which data the myVAILLANT API returns for different installations. Please turn on debug logging for this integration if you encounter another problem and add it to this issue.

**Comment by joselaya** [comment]
@signalkraft 
Hi, I am very happy today! This is already **Working**, I don't see all the entities (like for example the energy consumption)...but the most important thing, which is the boiler control, is already there!

Cooling Allowed in Circuit 0 
Domestic Hot Water 0
Error sensoHOME Ok
Online Status sensoHOME Ok 
**Zone 1 (online)**

I have been trying to integrate my boiler to HA for many months and I couldn't find anything... I thought about spending some extra money changing the thermostat, which means a BIG saving for me. 

Let me know how I can buy you a coffee and I'll be happy to do it! 👍

**Comment by edudele** [comment]
Good night,

Congratulations on the component I have installed.

We come from monitoring our machines with jonh30's ebusd, we have a lot of information. If you need any information or help, do not hesitate to ask.

**Comment by signalkraft** [comment]
@joselaya I'm happy to hear that! Positive feedback like that is good enough for me, but thanks for the coffee offer :heart:
