### ISSUE TITLE
Trigger legionella control program

### ISSUE THREAD

**Issue by Corvalan80** [signalkraft/mypyllant-component#200]
### Before requesting a new feature / a new sensor

- [ ] The feature I'm requesting exists in the myVAILLANT app, and I attached a screenshot
- [x] I tested the v0.7.3 and it's missing there
- [ ] I've [attached exported data](https://signalkraft.com/mypyllant-component/3-contributing/#contributing-test-data) of my system

### Describe the feature you want

The request to add screenshots from the myVAILLANT app already tells me that the feature request can't be fulfilled, but I was wondering whether one could have a switch like the hot water boost (switch.rumpelbude_domestic_hot_water_0_boost) to trigger a legionella control program.

I wanted to implement automation rules that will trigger such program if it is 

- not too cold
- there's access solar energy
- the last execution is more than 2 weeks ago
- etc.

**Comment by signalkraft** [comment]
Please [check the example in the documentation](https://signalkraft.com/mypyllant-component/1-automations/#legionella-protection). You should be able to put that automation on a switch, maybe ask in the HA forums.
