### ISSUE TITLE
vr 921 or vr 940 gateway

### ISSUE THREAD

**Issue by frans0180** [signalkraft/mypyllant-component#213]
hi

I want to use the mypyllant component for my Vaillant Arotherm heatpomp

the new gateway are VR940f    

so work the mypyllant also with the VR940f and the myValiant App ?

**Comment by CommanderROR9** [comment]
Yes, the VR940f works just fine.

**Comment by frans0180** [comment]
Ok thanks.  I have now the vr940 :-) 

But how can I get an API code ?

**Comment by CommanderROR9** [comment]
> Ok thanks. I have now the vr940 :-)
> 
> But how can I get an API code ?

You don't need an API Code. Just log into the Integration with your myVaillant credentials.

**Comment by frans0180** [comment]
Hi it works thanks !

is it possible to read the water flow current ?

**Comment by frans0180** [comment]
I don't know how to upload this.    But I have 33 identities but none of them have anything to do with water flow
