### ISSUE TITLE
VR921 Update failed?

### ISSUE THREAD

**Issue by tritter** [signalkraft/mypyllant-component#22]
When I start the plugin with a freshly migrated VR921 using myVaillant app I get this error:
```2023-08-25 21:17:07.001 DEBUG (MainThread) [custom_components.mypyllant] Creating API and logging in with mymail@gmail.co in realm germany
2023-08-25 21:17:09.165 DEBUG (MainThread) [custom_components.mypyllant] Refreshing SystemCoordinator
2023-08-25 21:17:09.165 DEBUG (MainThread) [custom_components.mypyllant] Starting async update data for SystemCoordinator
2023-08-25 21:17:09.165 DEBUG (MainThread) [custom_components.mypyllant] Waiting 119s until token refresh for mymail@gmail.co
2023-08-25 21:17:09.711 ERROR (MainThread) [custom_components.mypyllant] Error requesting myVAILLANT data: 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/firmware-update-required/```

**Comment by sparks1372** [comment]
I get the same error, also on a freshly migrated VR921

**Comment by Headkillah** [comment]
First, this is my heating config:

ecoTEC plus VCI 20/26CS/1-5 Boiler
Heating Controller sensoDIRECT 710
Vaillant VR 921 sensoNET
Vaillant Water Storage Tank VIH CL20S

I´ve got an update for my heating system. This updates included the change to the myvaillant app. Before i´ve used the Multimatic App and i was able to change, for example, the temperature.

With this app i´ve got only the sensors for energy consumption.

After adding my device(s) i´ve got the following debug messages:

`Error requesting myVAILLANT data: 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/firmware-update-required/cb96d3fb-25b4-461f-8adb-d3816d723dd5')`

And the "NoData" Messages for the following entities:

- binary_sensors
- sensors
- climate
- water heater

**Comment by signalkraft** [comment]
You may have better luck with the latest beta release, I made the update check optional. Let me know how it goes!

**Comment by froggi1930** [comment]
> First, this is my heating config:
> 
> ecoTEC plus VCI 20/26CS/1-5 Boiler Heating Controller sensoDIRECT 710 Vaillant VR 921 sensoNET Vaillant Water Storage Tank VIH CL20S
> 
> I´ve got an update for my heating system. This updates included the change to the myvaillant app. Before i´ve used the Multimatic App and i was able to change, for example, the temperature.
> 
> With this app i´ve got only the sensors for energy consumption.
> 
> After adding my device(s) i´ve got the following debug messages:
> 
> `Error requesting myVAILLANT data: 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/firmware-update-required/cb96d3fb-25b4-461f-8adb-d3816d723dd5')`
> 
> And the "NoData" Messages for the following entities:
> 
> * binary_sensors
> * sensors
> * climate
> * water heater

Did your system perform an update?

**Comment by Headkillah** [comment]
Yes, don't know what happened but now I have 25 entities and 4 devices :) And everything works like expected:)

Thx for your hard work :)

**Comment by froggi1930** [comment]
Did you restart the VR921, or just wait. My system does not perform any kind of update so far.

**Comment by tritter** [comment]
Yes here the API problem is also resolved!
