### ISSUE TITLE
Heat Curve control

### ISSUE THREAD

**Issue by CaptainHam** [signalkraft/mypyllant-component#222]
The MyVaillant app now allows Heat Curve control.

If this has been added to the API too, any plans to allow control of this via the HA integration?

![Screenshot_20241017-170848](https://github.com/user-attachments/assets/389878a6-a42d-4379-a8f7-363ef6faadab)

**Comment by Richardstables** [comment]
Not sure if this is related but since I updated the app it is now crashing when I try and look at the daily heating graph

**Comment by CaptainHam** [comment]
> Not sure if this is related but since I updated the app it is now crashing when I try and look at the daily heating graph

My app is not crashing but in any case this is related to a feature request on the HA integration, and not related to the MyVaillant app specifically

**Comment by frans0180** [comment]
Not sure if this is related but since I updated the app it is now crashing when I try and look at the daily heating graph

i have the same problem !

**Comment by Dzanar** [comment]
Tee my app crashing now...

**Comment by CaptainHam** [comment]
If your app is crashing, report it on the AppStore, this thread has nothing to do with the app!!!!!!!!

**Comment by fmoreiraausin** [comment]
> My app is not crashing but in any case this is related to a feature request on the HA integration, and not related to the MyVaillant app specifically

Very interesting, I hope they implement it, we should mention the creator of the integration

**Comment by HaraldKiessling** [comment]
> The MyVaillant app now allows Heat Curve control.
> 
> If this has been added to the API too, any plans to allow control of this via the HA integration?
> 
This feature would be very great. 
There would be super helpful automation-stories to implement. I had a lot ideas for this feature. How could i support to get this feature running?

**Comment by signalkraft** [comment]
Building this requires [reverse engineering](https://signalkraft.com/mypyllant-component/3-reverse-engineering/) the current version of the app, unfortunately none of the usual APK websites have a variant that runs on my phone (armv8) or an Android emulator (x86). Something must have changed in our Vaillant packages the app. If anyone can figure out the API endoints and payloads, I would be happy to give this a shot, since it seems useful.

**Comment by HaraldKiessling** [comment]
Oh great. I will take a look.

**Comment by HaraldKiessling** [comment]
I only found these 3 Calls:

PATCH https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/<systemId>/tli/circuit/<0 or 1>/heating-curve
{
  "heatingCurve": 0.3
}

POST https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/<systemId>/tli/circuit/<0 or 1>/heat-demand-limited-by-outside-temperature
{
  "heatDemandLimitedByOutsideTemperature": 14
}

PATCH https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/<systemId>/tli/circuit/<0 or 1>/min-flow-temperature-setpoint
{
  "minFlowTemperatureSetpoint": 32
}

**Comment by CaptainHam** [comment]
Many thanks, @signalkraft !
