### ISSUE TITLE
Version  myVAILLANT v0.8.19 will not update. 

### ISSUE THREAD

**Issue by bmargos** [signalkraft/mypyllant-component#233]
### Before submitting a new issue

- [x ] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [ x] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [ ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description
- removed Integration
- downloaded  myVAILLANT v0.8.21 in HACS
- installed Integration - but shows  myVAILLANT v0.8.19

Please describe what you were trying to do, what happened, and what you expected to happen.

### Logs

```
Put your debug logs here
Be careful not to include tokens, emails, and other personal information
```

**Comment by kibeki** [comment]
Exactly the same problem here.

**Comment by signalkraft** [comment]
Should be fixed

**Comment by bmargos** [comment]
Top - works.
