### ISSUE TITLE
Can't find where to enter myvaillant login details

### ISSUE THREAD

**Issue by pbbot70** [signalkraft/mypyllant-component#234]
### Before submitting a new issue

- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [ ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

I have installed the MyVaillant in HA using HACS. I see the MyVaillant under the HACS. But i can't find anywhere the option to enter my login infomation of vaillant information to make the connection to my heating system. The only thing the HACS MyVaillant shows is the update status the app is up to date. Where should i click to perform step 5 of the installation instructions

Sign in with the email & password you used in the myVAILLANT app (or MiGo app for Saunier Duval)

Kind regards,
Paul

### Logs

```
Put your debug logs here
Be careful not to include tokens, emails, and other personal information
```

**Comment by signalkraft** [comment]
https://www.home-assistant.io/getting-started/integration/
