### ISSUE TITLE
infromation from Hydraulic Station are missing

### ISSUE THREAD

**Issue by TommyD91** [signalkraft/mypyllant-component#235]
sice yesterday i can´t find the following the entitys
- electrical_energy_heating
- generated_heating
- energy_efficiency

i tried version v0.8.22 und v0.8.18. Does anyone have the same problem?

**Comment by ajvdw** [comment]
My Unitower shows zero's. I think it's right because I don't use the coil for heating. The heatpump handles it without the help of the electrical heating coil.

**Comment by signalkraft** [comment]
This is probably related to rate limiting on the energy data by Vaillant, but without a proper ticket I really can't tell. Please reopen an issue an fill out the template, if the issue persists and the many other issues about this problem don't help.
