### ISSUE TITLE
Feature Request: Real-Time Power Consumption Sensor

### ISSUE THREAD

**Issue by Tonio7456** [signalkraft/mypyllant-component#240]
### Feature Request: Real-Time Power Consumption Sensor

Hello,

First, thank you for the amazing work on this integration—it’s been incredibly helpful!

I’d like to request the addition of a real-time power consumption sensor (in Watts) as part of the myPyllant integration. The MyVaillant app appears to display this data, and it would be incredibly useful to have this available in Home Assistant for monitoring and automation purposes.

### Proposed Implementation

1. API Data Retrieval

It seems that the API might expose this data under a key like **currentPower**. The integration could be modified to fetch this data during updates. For example, in the **coordinator.py**:

```
async def _async_update_data(self):
    data = await self.api_client.fetch_data()
    return {
        "currentPower": data.get("currentPower"),
        # Other existing keys...
    }
```

2. Sensor Definition

A new sensor entity could be added to represent the real-time power consumption. 
This might look like the following in **sensor.py**:

```
class PowerSensor(SensorEntity):
    """Sensor for real-time power consumption."""

    def __init__(self, coordinator, device_info):
        super().__init__(coordinator)
        self._attr_name = "Current Power Consumption"
        self._attr_unique_id = f"{device_info['serialNumber']}_current_power"
        self._attr_device_info = device_info
        self._attr_unit_of_measurement = "W"
    
    @property
    def state(self):
        """Return the current power consumption."""
        return self.coordinator.data.get("currentPower")
```

3. Integration in Home Assistant
Once the sensor is added, users could display it in Home Assistant dashboards or use it in automations as **sensor.current_power_consumption**.

### Benefits
Energy Monitoring: Users can track their energy consumption in real-time.
Automations: Enable automations like adjusting heating when consumption exceeds a threshold.
If this feature is already planned or in progress, I’d love to know! Otherwise, I’d be happy to assist in testing or providing further details.

Thank you for considering this feature, and let me know if additional input is required.

Best regards,

_Originally posted by @Tonio7456 in https://github.com/signalkraft/mypyllant-component/discussions/173#discussioncomment-11309962_

**Comment by xxLeoxx93** [comment]
Real time power consumption in watts is already available. You just need to activate it in the addon options.

**Comment by Komaclo** [comment]
I would also like this and have checked but cannot see any addon options?

**Comment by Headkillah** [comment]
@Komaclo:

Go into Devices & services, search for integration "myVAILLANT" an click on it. Then klick on "configure" and scroll down to the end. There are 2 checkboxes "Fetch real-time statistics (not supported on every system)" and "Fetch real-time power usage (not supported on every system)"

**Comment by Komaclo** [comment]
Hi,

Brilliant thank you.



________________________________

**Comment by SJHowi** [comment]
So this entity has become unavailable for me after working for a few weeks since I enabled as described above, any ideas please?

**Comment by philsson** [comment]
> So this entity has become unavailable for me after working for a few weeks since I enabled as described above, any ideas please?

I came here to write the same. I removed the integration and added it again but these sensors did not come back. I also had this working previously

**Comment by camhef** [comment]
If your system shows real time data then this integration can show it - as long as you have followed the instructions above (also shown in the integration documentation).
Sometimes HA stops showing this useful data. This happens when myVaillant stops showing the data. 
I usually wait a few hours and then look at myVaillant again. When the data is showing in myVaillant just Reload this integration to get HA seeing the data again.
It always works for me.

**Comment by SJHowi** [comment]
been a few days now, it is always available in the myVailliant App, reloaded a few times.

![Screenshot 2024-12-20 095004](https://github.com/user-attachments/assets/888852b2-9577-4965-8a84-c72b4a660dfd)

**Comment by signalkraft** [comment]
Please [create a new issue](https://github.com/signalkraft/mypyllant-component/issues/new/choose) and fill out the template (test data, debug logs) so I can help you.

**Comment by schwachstelle** [comment]
What is your experience with working polling intervals for "Real-Time Power Consumption Sensor" without running into quota limits? At least near time would be nice...
