### ISSUE TITLE
Automatic and manual install fail on Home Assistant 2024.11.3 on RPi 4

### ISSUE THREAD

**Issue by roey-angel** [signalkraft/mypyllant-component#241]
Hi, 
Trying to install automatically via the link gives the following error:
```
Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.
```

I also copied the folder mypyllant into either:
`hassos-data/supervisor/homeassistant/custom_components `
or 
`hassos-data/supervisor/homeassistant/config/custom_components/`

But I still cannot see myVaillant integration.
I am using Home Assistant 2024.11.3 on RPi 4

Any ideas how to solve this?
Thanks!

**Comment by signalkraft** [comment]
See https://github.com/signalkraft/mypyllant-component/issues/242 for a possible fix
