### ISSUE TITLE
How can I enter the country?

### ISSUE THREAD

**Issue by LadidaHeyHey** [signalkraft/mypyllant-component#25]
![logininformation_myvaillant](https://github.com/signalkraft/mypyllant-component/assets/114108082/3528d790-ba5c-433f-8080-c97bb5aa00db)

I can't choose a country for the myVaillant integration in the beginning of the configuration. How can I change that? 

Thanks a lot

**Comment by signalkraft** [comment]
You seem to be on a very old version. Can you try [the latest beta release](https://hacs.xyz/docs/faq/beta/)? You should see brand and country options in this dialog.
