### ISSUE TITLE
Can't install - Invalid Credentials

### ISSUE THREAD

**Issue by jcss2503** [signalkraft/mypyllant-component#31]
### Before submitting a new issue

- [X] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [X] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [X] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

I can't install the component, invalid credentials message. I've had installed another integration working ok for years (previously uninstalled) , user and password is correct (I can login with MiGo App), country is Spain.

### Logs
```

2023-10-14 19:25:29.072 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://identity.vaillant-group.com/auth/realms/sdbg-spain-b2c/protocol/openid-connect/auth'), headers=<CIMultiDict()>)
2023-10-14 19:25:29.260 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='POST', url=URL('https://identity.vaillant-group.com/auth/realms/sdbg-spain-b2c/login-actions/authenticate'), headers=<CIMultiDict()>)


```

**Comment by signalkraft** [comment]
Thanks for posting logs, I removed a few things from your comment that contained session data. 

Accordin to the logs, the Vaillant login page returns this error:

> Usuario o contraseña incorrectos

Vaillant seems to think your user + password is wrong, there's not much I can do about that. Maybe the previous integration was using another API, than this integration is using (myVAILLANT and branded versions of it).

**Comment by jcss2503** [comment]
I tried changing the password in the MiGo APP y use the new password to install and same situation: "User or password incorrect".
But the thing is that I've received an email in my box warning me of the password change and this email comes from.... **NetAtmo**!!!
Could it be posssible that first versions of this climate has been registered in the NetAtmo cloud before the merge with Vaillant?  If is this way the question is how can I detach mi MiGo from the NetAtmo cloud?

**Comment by signalkraft** [comment]
Unfortunately I don't know anything about this, I just built the integration for myVAILLANT. You may have better luck on the Home Assistant community forums or contacting NetAtmo.
