### ISSUE TITLE
Q: Control of ventilation -  recoVAIR VAR 360/4

### ISSUE THREAD

**Issue by szflo** [signalkraft/mypyllant-component#32]
Is it possible to add ventilation control?

My ventilation device: VAR 360/4
One entity was discovered: "VAR 360/4 Consumed Electrical Energy Heating"

Other my devices like flexoCOMPACT and VR 921 works great. Thanks!

**Comment by signalkraft** [comment]
Unfortunately I don't have a device with ventilation controls to test with. If you're able to [reverse engineer](https://signalkraft.com/mypyllant-component/3-reverse-engineering/) your myVAILLANT app, I could help implement the necessary functionality.

**Comment by szflo** [comment]
Hi, thanx for respond. I'll try do that. For now I have problems with unpinning apk. 

```
CalledProcessError: Command 
'/home/s/android-unpinner/android_unpinner/vendor/platform_tools/linux/adb install 
--no-incremental myVAILLANT_2.11.0_Apkpure.unpinned.apk' returned non-zero exit status 1.

```

So I push unpinned file and force install on phone but I have this (CA cert was imported ) : 

```
[16:08:44.993][10.10.0.53:39214] client connect
[16:08:45.031][10.10.0.53:39214] server connect api.vaillant-group.com:443 (52.178.106.206:443)
[16:08:45.124][10.10.0.53:39214] Client TLS handshake failed. The client does not trust the proxy's certificate for api.vaillant-group.com (OpenSSL Error([('SSL routines', '', 'sslv3 alert certificate unknown')]))
[16:08:45.125][10.10.0.53:39214] client disconnect
[16:08:45.126][10.10.0.53:39214] server disconnect api.vaillant-group.com:443 (52.178.106.206:443)
[16:08:45.224][10.10.0.53:39216] client connect
[16:08:45.266][10.10.0.53:39216] server connect api.vaillant-group.com:443 (52.178.106.206:443)
[16:08:45.409][10.10.0.53:39216] Client TLS handshake failed. The client does not trust the proxy's certificate for api.vaillant-group.com (OpenSSL Error([('SSL routines', '', 'sslv3 alert certificate unknown')]))

```

I will try later on other phone with rooted android.

**Comment by szflo** [comment]
I can't force myVaillant app to work via proxy. I can login to app but devices and info about temp etc is unavailable.


[19:04:37.409][10.10.0.62:46770] server connect api.vaillant-group.com:443 (52.178.106.206:443)
[19:04:37.410][10.10.0.62:46786] server connect api.vaillant-group.com:443 (52.178.106.206:443)
[19:04:37.411][10.10.0.62:46782] server connect api.vaillant-group.com:443 (52.178.106.206:443)
[19:04:37.548][10.10.0.62:46782] Client TLS handshake failed. The client does not trust the proxy's certificate for api.vaillant-group.com (OpenSSL Error([('SSL routines', '', 'sslv3 alert certificate unknown')]))
[19:04:37.549][10.10.0.62:46786] Client TLS handshake failed. The client does not trust the proxy's certificate for api.vaillant-group.com (OpenSSL Error([('SSL routines', '', 'sslv3 alert certificate unknown')]))
[19:04:37.550][10.10.0.62:46770] Client TLS handshake failed. The client does not trust the proxy's certificate for api.vaillant-group.com (OpenSSL Error([('SSL routines', '', 'sslv3 alert certificate unknown')]))
[19:04:37.551][10.10.0.62:46766] Client TLS handshake failed. The client does not trust the proxy's certificate for api.vaillant-group.com (OpenSSL Error([('SSL routines', '', 'sslv3 alert certificate unknown')]))

**Comment by signalkraft** [comment]
Later versions of the app seem to use stricter certificate pinning or chain verification. There's probably ways to circumvent this with a rooted phone, but I haven't had the time to try that.

**Comment by signalkraft** [comment]
I've had some time to play around with this today, it appears that https://github.com/shroudedcode/apk-mitm works (for now):

```bash
apk-mitm myVAILLANT_2.10.1_Apkpure.xapk
adb install-multiple com.vaillantgroup.enduserapp.vaillant.apk config.mdpi.apk config.fr.apk config.en.apk config.arm64_v8a.apk
```

Proxy settings etc. stay the same.

**Comment by szflo** [comment]
Great! apk-mitm patch apk and I can catch requests:

PATCH https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/fe9c8348-5202-440f-b0cf-56a08aca1635/tli/ventilation/0/operation-mode HTTP/1.1
JSON
{
    "operationMode": "NORMAL"
}
This one change ventilation mode to "normal"

and to reduced:
{
    "operationMode": "REDUCED"
}

In ventilation settings I have: 
1. weekly planner
2. operation mode (normal, reduced and time control)
3. normal: level (1-6)
4. reduced: level (1-6)

Tell me what do you need exactly, I'm happy to help ;)
Thanks!

**Comment by szflo** [comment]
PATCH https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/fe9c8348-5202-440f-b0cf-56a08aca1635/tli/ventilation/0/fan-stage HTTP/1.1

{
    "maximumFanStage": 2,
    "type": "NIGHT"
}

reduced mode ^ and normal mode:

{
    "maximumFanStage": 2,
    "type": "DAY"
}

**Comment by signalkraft** [comment]
Cool!

Could you also generate test data and attach it? You'll find a description in the documentation page. It should already be anonymized (serial numbers, etc.).

**Comment by szflo** [comment]
[vaillant.tar.gz](https://github.com/signalkraft/mypyllant-component/files/13226651/vaillant.tar.gz)

test_data are attached

**Comment by signalkraft** [comment]
Thanks a lot, I've played around with that and added some entities in https://github.com/signalkraft/mypyllant-component/releases/tag/v0.5.5b1

I have no easy way of testing this, so please let me know how it works for your system!

**Comment by szflo** [comment]
Thank you! 
After installation I have found additional device "VAR 360/4" without any entities. Old VAR 360/4 device still exist and have one entity "VAR 360/4 Consumed Electrical Energy Heating"
Devices:
![v1](https://github.com/signalkraft/mypyllant-component/assets/24790983/a9df7ec9-1a8a-4302-bb8d-dd340a27aca0)

![v2](https://github.com/signalkraft/mypyllant-component/assets/24790983/ee00e582-1e8e-4a1e-b934-2d3c991b785d)
Log file:
[home-assistant_2023-11-02T08-26-32.065Z.log](https://github.com/signalkraft/mypyllant-component/files/13236302/home-assistant_2023-11-02T08-26-32.065Z.log)

Integration was upgraded to newest beta and reinstalled.

**Comment by signalkraft** [comment]
Please try https://github.com/signalkraft/mypyllant-component/releases/tag/v0.5.5b2 - the error in your logs should be fixed in that. New ones may crop up, though.

**Comment by szflo** [comment]
I found entity "climate.ventilation_0
![var2](https://github.com/signalkraft/mypyllant-component/assets/24790983/068594c1-31fb-4337-8890-98dae77b8d20)

and add dashbord:
![var3](https://github.com/signalkraft/mypyllant-component/assets/24790983/b8c63a81-9a39-42af-98d6-7bda01c3c004)
![var4](https://github.com/signalkraft/mypyllant-component/assets/24790983/e380980b-9c49-42aa-89d1-b5bfd35fad5f)
![var5](https://github.com/signalkraft/mypyllant-component/assets/24790983/9fbc5de5-b97e-48e9-8770-0a40f89c1dd7)

I can change ventilation level but it's a bit clunky ;)
Thanks a lot for your support.

**Comment by signalkraft** [comment]
Yeah, that looks pretty janky. You can try https://github.com/signalkraft/mypyllant-component/releases/tag/v0.5.5b3 - I used a fan entity there, instead.

But the fan speed control makes no sense for me. According to your recorded data, there's a day & night max fan speed - but there's no info if the ventilation entity is in day or night mode. So I assumed that reduced mode means night mode. So now if reduced mode is enabled, it sets the maximum night speed, and for every other mode it sets the day speed.

I suppose there's no other control where you just overwrite the fan speed, without day / night settings?

**Comment by szflo** [comment]
I have v0.5.5b3 and can't find fan entity. My logs:

[home-assistant_mypyllant_2023-11-05T13-41-35.970Z.log](https://github.com/signalkraft/mypyllant-component/files/13259736/home-assistant_mypyllant_2023-11-05T13-41-35.970Z.log)

You can't control fan speed in ventilation, this work in other way. In myVaillant app I have two modes: Normal (or day mode) and Reduced (night). You need assign to those modes ventilation device mode (from 1 to 6). After that you can choose between Normal and Reduced mode or make weekly plan (symilar to heating planner where you can set intervals for Normal or Reduced mode). 
Unfortunately for now ventilation info and settings in myVaillant app is very poor. On ventilation device we can read much more interesting info. I hope they add more options to the app later.

**Comment by signalkraft** [comment]
I guess then the version with the climate entity makes the most sense, even though it looks terrible. Right?

**Comment by szflo** [comment]
I only tested the climate entity, the fan entity is not available. Better a weak one than none at all ;)
Thanks!

**Comment by Waschbeton** [comment]
Also no climate entity for my var 360/4 e on vr 900 controller.

**Comment by szflo** [comment]
> so is this suppose to work with any RecoVair System? I've a RecoVair260/4 and the entity is not visible

Works with my 360/4, should work similarly with 260. Do you have ventilation control in the myVaillant app?

my entiti in ha: climate.home_ventilation_var_360_4_climate

**Comment by Waschbeton** [comment]
which version are you on? ventilation control (but no ventilation boost available) is working in the myvaillant app for me.

**Comment by szflo** [comment]
Latest beta but v0.7.3 also works ok. 
The myVaillant app is weak and the HA integration can only change the ventilation mode - normal or low (these modes can be assigned in the app).

**Comment by VaillantHassIo** [comment]
> > so is this suppose to work with any RecoVair System? I've a RecoVair260/4 and the entity is not visible
> 
> Works with my 360/4, should work similarly with 260. Do you have ventilation control in the myVaillant app?
> 
> my entiti in ha: climate.home_ventilation_var_360_4_climate

yes i do
