### ISSUE TITLE
Home assistant HACS upgrade

### ISSUE THREAD

**Issue by ear9mrn** [signalkraft/mypyllant-component#33]
Not sure this is the right place to ask...

Just upgraded to a the latest version. 0.3.2 (home assistant HACS) and a couple of the entities have disappeared.

missing entities:
outside_temperature
system_water_pressure
water_pressure_ecotec
system_mode

I have a sensoCOMFORT VRC720 (wired), ecoTec Plus 624, VR66/2 control center with sensoNET and a VR10 probe (outdoor temp)

Thanks,

Pete.

**Comment by minosrex** [comment]
Update: I uninstalled everything, rebooted, installed v0.5.2, rebooted, and installed the component. This gave me 4 devices and 5 entities, but the Zone 1 device (normally containing the temp sensors and the climate entity) was empty (no entities). However, after a third and final server reboot the entities are now back!

**Comment by signalkraft** [comment]
@ear9mrn let me know if you still have this issue, but since it's on an old version I'm closing this.
