### ISSUE TITLE
Error fetching data

### ISSUE THREAD

**Issue by Benni1123** [signalkraft/mypyllant-component#37]
Hi!
The MyVaillant integration worked 8h... 
now i recieved this error:
`Error fetching myVAILLANT data: Quota Exceeded on https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/claims, skipping update of myVAILLANT data for another 10800s`

I can't use the MyVaillant App (Error since 4h..)
I had set the data query to 10 seconds.  Is this the problem?

**Comment by signalkraft** [comment]
Yes, I would imagine that querying every 10s gets you blocked after some time. Probably best to return to the default 60s, deactive the integration, wait for your app to return to normal, and then switch the integration back on.

I've added a note to the option field that warns people about this problem.

**Comment by Benni1123** [comment]
> Yes, I would imagine that querying every 10s gets you blocked after some time. Probably best to return to the default 60s, deactive the integration, wait for your app to return to normal, and then switch the integration back on.
> 
> I've added a note to the option field that warns people about this problem.

Thank you! Is 60s safe? I do not want to be blocked again

**Comment by signalkraft** [comment]
Jup, that's been working fine for me.
