### ISSUE TITLE
¿Lost Token?

### ISSUE THREAD

**Issue by edudele** [signalkraft/mypyllant-component#4]
Hello,

The integration has given this error, possibly due to a failure with the token.

I have restarted the integration Settings->Devices and Services and it worked again without problem.

> 2023-03-03 14:11:23.868 ERROR (MainThread) [custom_components.mypyllant] Error requesting myVAILLANT data: 400, message='Bad Request', url=URL('https://vaillant-prod.okta.com/oauth2/default/v1/token')
2023-03-03 15:11:16.863 ERROR (MainThread) [custom_components.mypyllant] Error requesting myVAILLANT data: 400, message='Bad Request', url=URL('https://vaillant-prod.okta.com/oauth2/default/v1/token')
2023-03-03 15:11:17.580 ERROR (MainThread) [custom_components.mypyllant] Error requesting myVAILLANT data: 400, message='Bad Request', url=URL('https://vaillant-prod.okta.com/oauth2/default/v1/token')

**There has been no internet connection.**

**Comment by signalkraft** [comment]
I had the same error as you around the same time. It hasn't happened since, so maybe sth. was wrong with the API. I'll keep this open, in case it happens again let me know!

**Comment by edudele** [comment]
> Tuve el mismo error que tú casi al mismo tiempo. No ha sucedido desde entonces, así que tal vez algo. estaba mal con la API. Mantendré esto abierto, en caso de que vuelva a suceder, ¡házmelo saber!

Ok

**Comment by edudele** [comment]
Good morning,
The problem has not repeated, close the issues and if it happens again I will reopen it.

Possibly it is due to the Vaillant cloud, because it fails a lot, last week we spent 3 days without the application, it was a problem recognized by Vaillant.

Possibly it will happen again when the Vaillant endpoint goes down.

**Comment by mc-mario** [comment]
This has also been happening to me lately;
```python3
  File "/Users/mariomblu/GitHub/myPyllant/tests/generate_test_data.py", line 54, in main
    async with MyPyllantAPI(user, password) as api:
  File "/Users/mariomblu/GitHub/myPyllant/src/myPyllant/api.py", line 83, in __aenter__
    await self.login()
  File "/Users/mariomblu/GitHub/myPyllant/src/myPyllant/api.py", line 104, in login
    raise Exception(login_json["errorSummary"])
Exception: Authentifizierung fehlgeschlagen
Unclosed client session
```

A couple days ago I was prompted to update myVaillant app to use an improved "new login" system. Maybe they are deprecating the old endpoint

**Comment by edudele** [comment]
It has happened again.

> state = self._stringify_state(available)
2023-03-07 13:24:50.426 ERROR (MainThread) [custom_components.mypyllant] Error requesting myVAILLANT data: 400, message='Bad Request', url=URL('https://vaillant-prod.okta.com/oauth2/default/v1/token')
2023-03-07 13:44:16.508 ERROR (MainThread) [custom_components.mypyllant] Error requesting myVAILLANT data: 400, message='Bad Request', url=URL('https://vaillant-prod.okta.com/oauth2/default/v1/token')
2023-03-07 13:44:17.156 ERROR (MainThread) [custom_components.mypyllant] Error requesting myVAILLANT data: 400, message='Bad Request', url=URL('https://vaillant-prod.okta.com/oauth2/default/v1/token')

I have included this in my config:

>logger:
  logs:
    custom_components.mypyllant: debug
    myPyllant: debug
    
Regarding the last authentication after the update, the same thing happened to me, it seems to me that they use OAuth 2.0, since that login came out of a website using a federated cloud Web App login.

I may be wrong, but it is possible that the download of the new token in the current version is done by OAuth.

**Comment by edudele** [comment]
After restarting home assistant with the logger on, two errors:

> Logger: homeassistant.config_entries
Source: custom_components/mypyllant/__init__.py:34
Integration: myVAILLANT ([documentation](https://github.com/signalkraft/myPyllant), [issues](https://github.com/signalkraft/issues))
First occurred: 15:50:31 (1 occurrences)
Last logged: 15:50:31
Error setting up entry xxxxx@gmail.com for mypyllant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mypyllant/__init__.py", line 34, in async_setup_entry
    await api.login()
  File "/usr/local/lib/python3.10/site-packages/myPyllant/api.py", line 104, in login
    raise Exception(login_json["errorSummary"])
Exception: Authentifizierung fehlgeschlagen


> Logger: myPyllant.api
Source: custom_components/mypyllant/__init__.py:34
Integration: myVAILLANT ([documentation](https://github.com/signalkraft/myPyllant), [issues](https://github.com/signalkraft/issues))
First occurred: 15:50:31 (1 occurrences)
Last logged: 15:50:31
Could not log in, got status 401 this response: {'errorCode': 'E0000004', 'errorSummary': 'Authentifizierung fehlgeschlagen', 'errorLink': 'E0000004', 'errorId': 'oae-W27IQvsTry1MHxO3FpSkw', 'errorCauses': []}

The German translation of
Authentifizierung fehlgeschlagen -> Authentification failed

And devices:
![image](https://user-images.githubusercontent.com/2486525/223461271-f184bfdd-55e9-454f-be78-7d76b7770359.png)

This new update has a lot of changes in authentication so it seems

**Comment by edudele** [comment]
Performing the wipe and recreating the device, still fails to authenticate.
![image](https://user-images.githubusercontent.com/2486525/223462735-b0024143-93df-4c5f-a148-40a45b15f5be.png)

**Comment by signalkraft** [comment]
Vaillant changed the login workflow completely, see https://github.com/signalkraft/myPyllant/issues/7#issuecomment-1459049586

Latest version should work again!

**Comment by blizarazu** [comment]
It does not work for me either. I uninstalled the previous version before installing v0.1.0, and after entering my credentials, nothing happens. There is no information about the component in the logs.

**Comment by ardyp87** [comment]
Having the same issue, no error in the log. Thanks.

**Comment by signalkraft** [comment]
I tested the setup with a blank HA docker container, it works for me.

When you log into the myVaillant app, do you get a browser window like this, or do you enter username and password in the app?

![image](https://user-images.githubusercontent.com/3762829/223840744-e6490233-3f46-4c02-abf4-47c1089036d7.png)

If you get the browser window, could you share the URL you are getting? In my case it starts with `https://identity.vaillant-group.com/auth/realms/vaillant-germany-b2c/protocol/openid-connect/auth`.

Maybe there are different realms (groups) in Vaillant's new authentication, in my case it's `vaillant-germany-b2c`. I would need to know which addresses you are seeing to validate that.

**Comment by ardyp87** [comment]
https://identity.vaillant-group.com/auth/realms/vaillant-italy-b2c/protocol/openid-connect/auth?client_id=myvaillant&redirect_uri=enduservaillant.page.link%3A%2F%2Flogin&login_hint=[emailaddress]&response_mode=fragment&response_type=code&scope=offline_access%20openid&code_challenge=******&code_challenge_method=S256


That’s the link I got.

**Comment by edudele** [comment]
Muy link

https://identity.vaillant-group.com/auth/realms/vaillant-spain-b2c/protocol/openid-connect/auth?client_id=myvaillant&redirect_uri=enduservaillant.page.link%3A%2F%2Flogin&login_hint=edudele%40gmail.com&response_mode=fragment&response_type=code&scope=offline_access%20openid&code_challenge=xa-z90X-gNgxl3CKDVtT3NhjF7bGsI2iGmmIzFDwgY0&code_challenge_method=S256

**Comment by edudele** [comment]
My link, Spain

https://identity.vaillant-group.com/auth/realms/vaillant-spain-b2c/protocol/openid-connect/auth?client_id=myvaillant&redirect_uri=enduservaillant.page.link%3A%2F%2Flogin&login_hint=edudele%40gmail.com&response_mode=fragment&response_type=code&scope=offline_access%20openid&code_challenge=*****&code_challenge_method=S256

**Comment by minosrex** [comment]
https://identity.vaillant-group.com/auth/realms/vaillant-belgium-b2c/protocol/openid-connect/auth?client_id=myvaillant&redirect_uri=enduservaillant.page.link%3A%2F%2Flogin&login_hint=***EMAIL***&response_mode=fragment&response_type=code&scope=offline_access%20openid&code_challenge=****&code_challenge_method=S256

Belgium

**Comment by edudele** [comment]
My link, Spain

https://identity.vaillant-group.com/auth/realms/vaillant-spain-b2c/protocol/openid-connect/auth?client_id=myvaillant&redirect_uri=enduservaillant.page.link%3A%2F%2Flogin&login_hint=***email***%40gmail.com&response_mode=fragment&response_type=code&scope=offline_access%20openid&code_challenge=*****&code_challenge_method=S256

**Comment by ardyp87** [comment]
Tried uninstalling and reinstalling the component, I’m now unable to login.

**Comment by signalkraft** [comment]
I added a country selection in version `v0.1.1`. After updating and restarting home assistant, please click on configure on myVaillant in [integrations](https://my.home-assistant.io/redirect/integrations/) and select your country. Afterwards reload the integration.

If you weren't able to login when adding the integration, you should see a country selection after username and password.

**Comment by edudele** [comment]
V0.1.1 login perfectly.

Thank you for your work.

We keep in observation...

**Comment by mc-mario** [comment]
Can confirm it works great 🙌🏻 !

**Comment by ardyp87** [comment]
Thanks, this fixed the issue for me after uninstall and reinstall.

**Comment by Alllfff** [comment]
Perfect, works fine now

**Comment by Micky2149** [comment]
Thanks

**Comment by MP14588** [comment]
Thank you. Now the log in works perfectly.
Unfortunately no devices are listed in the integration.

I report some errors:

Logger: custom_components.mypyllant
Source: custom_components/mypyllant/__init__.py:139
Integration: myVAILLANT (documentation, issues)
First occurred: 8 marzo 2023 alle ore 23:26:08 (4 occurrences)
Last logged: 21:59:45

Unexpected error fetching myVAILLANT data: 1 validation error for Zone current_room_temperature field required (type=value_error.missing)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/mypyllant/__init__.py", line 139, in _async_update_data
    data = [
  File "/config/custom_components/mypyllant/__init__.py", line 139, in <listcomp>
    data = [
  File "/usr/local/lib/python3.10/site-packages/myPyllant/api.py", line 200, in get_systems
    system = System(
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 114, in __init__
    self.zones = [Zone(system_id=self.id, **z) for z in self._raw_zones]
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 114, in <listcomp>
    self.zones = [Zone(system_id=self.id, **z) for z in self._raw_zones]
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Zone
current_room_temperature
  field required (type=value_error.missing)

And the other one:

Logger: homeassistant.components.binary_sensor
Source: custom_components/mypyllant/binary_sensor.py:32
Integration: Sensore binario (documentation, issues)
First occurred: 8 marzo 2023 alle ore 23:26:09 (4 occurrences)
Last logged: 21:59:46

Error while setting up mypyllant platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mypyllant/binary_sensor.py", line 32, in async_setup_entry
    for index, system in enumerate(coordinator.data):
TypeError: 'NoneType' object is not iterable

Any help?

Thanks

**Comment by signalkraft** [comment]
I'm closing this and moving your issue to a new ticket @MP14588
