### ISSUE TITLE
Data not aviable

### ISSUE THREAD

**Issue by Benni1123** [signalkraft/mypyllant-component#41]
Hello!

I keep having the problem that the heating control is not available. Reloading helps briefly, but it still stops too often. I have tested the current beta versions and now the stable version. It is the same problem.
![image](https://github.com/signalkraft/mypyllant-component/assets/37271495/0d002a28-fd2b-4c46-99e6-9856118d321e)

I have this problem every 2-3 days at 3 a.m. (that's when I do an HA reboot)

**Comment by Benni1123** [comment]
I found this at the logs:
![image](https://github.com/signalkraft/mypyllant-component/assets/37271495/54af0f01-2b6f-4cc5-b335-5a7ad9669d05)

**Comment by signalkraft** [comment]
`Cannot connect to host` seems like a problem with your internet connection (or a temporary issue with Vaillant's API).

**Comment by Benni1123** [comment]
> `Cannot connect to host` seems like a problem with your internet connection (or a temporary issue with Vaillant's API).

I have tested it further. It's not because of my internet connection. I have the problem when the update is set to 60 seconds. It works on 180 seconds. But I will go down slowly to test it further.
