### ISSUE TITLE
Can't see Ecotec data in Hybrid system. All other data are OK

### ISSUE THREAD

**Issue by Gio-dot** [signalkraft/mypyllant-component#46]
### Before submitting a new issue

- [x] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Hi, I own an Hybrid system with aroTherm, Ecotec plus, Hydraulic station and Aurostor,  sensoCOMFORT 720 and VR 92 as in the Vaillant scheme attached. System scheme is n.12 as is set in  sensoCOMFORT 720 parameters. In myVaillant app i can see arotherm electricity consumption and ecotec gas consumption data. 
In my pyllant data instead, ecotec data are totally missed and strangely reported system scheme is "1" and not "12". I can see all other data. There is something i'm missing?

![Immagine 2023-11-17 023511](https://github.com/signalkraft/mypyllant-component/assets/55327160/f90d90b3-5db2-46a4-9c99-49af5337e6da)
![Immagine 2023-11-17 023631](https://github.com/signalkraft/mypyllant-component/assets/55327160/ca911661-bb5f-4bd4-b7e9-180d6f39f24d)
![Immagine 2023-11-17 023414](https://github.com/signalkraft/mypyllant-component/assets/55327160/b2a8052c-7ff2-4152-9218-4c6e714249e0)

### Logs

```
Put your debug logs here
Be careful not to include tokens, emails, and other personal information
```

**Comment by signalkraft** [comment]
The system scheme is odd, but it comes straight from the API like that.

Searching for energy or gas entities in the Developers > states list also doesn't show anything, right?

Could you try to install the mypyllant library and [export data](https://github.com/signalkraft/mypyllant#exporting-data-about-your-system) with the `-d` argument? Then look for the bits that are related to gas consumption and attach them here.

**Comment by signalkraft** [comment]
I've added services for export and generate test data in the latest release. Could you try running those from Developer tools > services and posting the results here?
