### ISSUE TITLE
Error setting up entry for mypyllant

### ISSUE THREAD

**Issue by Benni1123** [signalkraft/mypyllant-component#49]
Hi!
I cant use the myVaillant integration since today. 
I have the latest version. I have also reinstalled it.
The myVaillant app works.(VR921, Vaillant EcoTec plus vc 20 cs/1-5)
 Here are the error:

`Error setting up entry EMAIL@gmail.com for mypyllant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/__init__.py", line 80, in async_setup_entry
    await daily_data_coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/__init__.py", line 217, in _async_update_data
    data[system.id] += [da async for da in device_data]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/__init__.py", line 217, in <listcomp>
    data[system.id] += [da async for da in device_data]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 357, in get_data_by_device
    async with self.aiohttp_session.get(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError: Global task timeout`

**Comment by kivster** [comment]
```
Core v2023.11.2
Supervisor v2023.11.3
Operating System v11.1
Frontend v20231030.2
HACS v1.33.0
Vaillant VR940f v0404.01.15
```


Same here, integration stops working after v6 upgrade. Tried reloading, restarted HA and restarting the myVaillant Connect without resolution.

The myVailant app also stopped working immediately after updating my myPyllant to v6.0.

![image](https://github.com/signalkraft/mypyllant-component/assets/6528858/d8a1679e-d99c-41ed-a157-fcbb13247c48)

![image](https://github.com/signalkraft/mypyllant-component/assets/6528858/2c68c901-e24c-42d0-a301-c442fa761d2a)

```
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 19:03:50 (2 occurrences)
Last logged: 20:44:33

Error setting up entry josef@nankivell.io for mypyllant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/__init__.py", line 80, in async_setup_entry
    await daily_data_coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/__init__.py", line 209, in _async_update_data
    async for system in await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 300, in get_systems
    async with self.aiohttp_session.get(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError: Global task timeout
```

**Comment by Benni1123** [comment]
`[139693615980096] 401, message='Unauthorized', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/xxxxxxxx/tli/zones/0/quick-veto')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mypyllant/climate.py", line 454, in async_set_preset_mode
    await self.coordinator.api.cancel_quick_veto_zone_temperature(
  File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 469, in cancel_quick_veto_zone_temperature
    return await self.aiohttp_session.delete(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/xxxxxxxxxxxxxxxxxxx/tli/zones/0/quick-veto')
`
When I receive data, I cannot change anything (error 403)

**Comment by Benni1123** [comment]
> ```
> Core v2023.11.2
> Supervisor v2023.11.3
> Operating System v11.1
> Frontend v20231030.2
> HACS v1.33.0
> Vaillant VR940f v0404.01.15
> ```
> 
> Same here, integration stops working after v6 upgrade. Tried reloading, restarted HA and restarting the myVaillant Connect without resolution.
> 
> The myVailant app also stopped working immediately after updating my myPyllant to v6.0.
> 
> I wonder if I've been temporarily banned for too much app activity from the update.
> 
> ```
> Logger: homeassistant.config_entries
> Source: config_entries.py:402
> First occurred: 19:03:50 (2 occurrences)
> Last logged: 20:44:33
> 
> Error setting up entry josef@nankivell.io for mypyllant
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/mypyllant/__init__.py", line 80, in async_setup_entry
>     await daily_data_coordinator.async_refresh()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in async_refresh
>     await self._async_refresh(log_failures=True)
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
>     self.data = await self._async_update_data()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/mypyllant/__init__.py", line 209, in _async_update_data
>     async for system in await self.hass.async_add_executor_job(
>   File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 300, in get_systems
>     async with self.aiohttp_session.get(
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
>     self._resp = await self._coro
>                  ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
>     await resp.start(conn)
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
>     message, payload = await protocol.read()  # type: ignore[union-attr]
>                        ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
>     await self._waiter
> asyncio.exceptions.CancelledError: Global task timeout
> ```
> 
> ![image](https://user-images.githubusercontent.com/6528858/284091290-d8a1679e-d99c-41ed-a157-fcbb13247c48.png)
> 
> ![image](https://user-images.githubusercontent.com/6528858/284091306-2c68c901-e24c-42d0-a301-c442fa761d2a.png)

The app works for me. But it's extremely slow.
I did the v6 update 4 days ago. It worked until just now.

**Comment by Benni1123** [comment]
I have now downgraded to 0.5.4. It is now very slow (like the myvaillant app, applying settings, updating information). But it works so far (since about 20 min).

**Comment by kivster** [comment]
> I have now downgraded to 0.5.4. It is now very slow (like the myvaillant app, applying settings, updating information). But it works so far (since about 20 min).
> 
> 

That *may* have been a coincidence for you. I've done nothing and my app is now partly working; controls are back but no data. Also extremely slow.

![image](https://github.com/signalkraft/mypyllant-component/assets/6528858/09a4eab5-c05e-4dbd-884a-908db24f5fd0)

![image](https://github.com/signalkraft/mypyllant-component/assets/6528858/1f459047-3c5f-48fa-83cc-4d81c82677ab)

**Comment by Benni1123** [comment]
Okay.. I can't change the temperature in HA now... (0.5.4)
![image](https://github.com/signalkraft/mypyllant-component/assets/37271495/7a582fa0-5e33-43e8-82ad-ff5cbf45bcc6)

**Comment by Benni1123** [comment]
> > I have now downgraded to 0.5.4. It is now very slow (like the myvaillant app, applying settings, updating information). But it works so far (since about 20 min).
> 
> That _may_ have been a coincidence for you. I've done nothing and my app is now partly working; controls are back but no data. Also extremely slow.
> 
> ![image](https://user-images.githubusercontent.com/6528858/284092998-09a4eab5-c05e-4dbd-884a-908db24f5fd0.png)
> 
> ![image](https://user-images.githubusercontent.com/6528858/284093008-1f459047-3c5f-48fa-83cc-4d81c82677ab.png)

i can see all the data in the app. sometimes it takes up to 5 minutes to load...

**Comment by kivster** [comment]
The myVAILLANT app has been working for a while until I ran reload on the v0.6.0 myPyllant integration again. It immediately broke the app again while reloading - I saw it happen in real time.

![image](https://github.com/signalkraft/mypyllant-component/assets/6528858/cb1d14f3-e8cd-4c92-b486-c7231e4b7ad9)

**Comment by Benni1123** [comment]
I have the feeling that 0.5.4 runs better. But I can sometimes change the temperature, sometimes I get the error 401.

**Comment by pnm1977** [comment]
I had a similar experience yesterday but believed it to be an issue with the Vaillant servers rather than this integration. My app started running slow long before seeing an issue in HASS. Around 10pm UK time everything started working again. I was already on v0.6.0 a while before the issues started and it was working fine. Since 10pm last night it's still working fine.

**Comment by kivster** [comment]
The slowness may have been an issue with their cloud. However, I can re-create the myVAILLANT app and api breaking by upgrading to v0.6.0 (tested twice). After upgrade, as myPyllant tries to initialise,the app says the gateway cannot be contacted and my time zone is out of sync; sort of feels like first time setup.

After a while of waiting some myVAILLANT app functionality comes back, like control but not usage data. MyPyllant HA integration never starts working again on v0.6.0 for me.

I had to rollback myPyllant to v5.4.5, which restored HA functionality. 

I then had to reinstall the myVAILLANT app on my iPhone, which was the only way to get the data screen in the app working again.

Now I'm back with everything working, but upgrading myPyllant to v0.6.0 would break it again (tested a few times).

**Comment by kivster** [comment]
I upgraded myPyllant to v0.6.0 without issue. I guess performing an upgrade while Vaillant had whatever issues they had in their cloud last night must have caused the bad outcome.

**Comment by signalkraft** [comment]
Like you said, I think there was a downtime on Vaillant's part that coincided with your setup. Previous versions shouldn't really affect this. I'm in the process of improving error messages around this sort of failure.

**Comment by kivster** [comment]
> Like you said, I think there was a downtime on Vaillant's part that coincided with your setup. Previous versions shouldn't really affect this. I'm in the process of improving error messages around this sort of failure.

Yes, you're right. Thanks for what you do on the project, it's great!

**Comment by kivster** [comment]
Got a confirmation from Vaillant that they were doing maintenance at the weekend and beyond.

> We were aware of issues where the EMF data was missing since the 6th November.

Maintenance has been carried out over the weekend and past few days

The final update was completed this afternoon and the issue should now be resolved

We apologise for any inconvenience this has caused and thank you for your patience whilst we get this resolved. 

Kind regards,
Vaillant Group UK

**Comment by signalkraft** [comment]
Thanks for posting this update, I'll close this then.
