### ISSUE TITLE
Outdoor Temp Sensor unknown at 0.0

### ISSUE THREAD

**Issue by pnm1977** [signalkraft/mypyllant-component#51]
### Before submitting a new issue

- [y] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [y] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [y] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

The sensor.outdoor_temperature reports "Unknown" when the temperature is exactly 0.0. It reports fine either side of zero but always goes unknown at zero.

### Logs

N/A

**Comment by signalkraft** [comment]
Thanks for the report, that should be fixed in the latest version!

**Comment by pnm1977** [comment]
Thanks for the quick fix. Just upgraded and will monitor over the next few days. It’s due to freeze overnight for most of the week.
