### ISSUE TITLE
2 HP cascaded / 2 WP in Kaskade

### ISSUE THREAD

**Issue by andyx87** [signalkraft/mypyllant-component#52]
### Before submitting a new issue

- [X] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [X] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [X] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Dear GitHub Community,

I am using the MyVaillant integration for Home Assistant, and I have two heat pumps at home that are cascaded (Systemschema 8). The issue I'm facing is that I can only retrieve data for one of the heat pumps in the integration, specifically the energy data. I cannot access the data for the second heat pump, and the second heat pump is not displayed in the integration.

Has anyone of you had similar experiences or found a solution to this problem? I would appreciate your help or advice on how to successfully integrate both heat pumps into Home Assistant.

Thank you in advance for your support!

Best regards

------------------------------

Liebe GitHub-Community,

Ich nutze die MyVaillant Integration für Home Assistant und habe zu Hause zwei Wärmepumpen, die in Kaskade geschaltet sind (Systemschema 8). Das Problem, das ich habe, ist, dass ich in der Integration nur die Daten für eine Wärmepumpe abrufen kann, insbesondere die Energiedaten. Die Daten für die zweite Wärmepumpe kann ich nicht abrufen, und die zweite Wärmepumpe wird in der Integration nicht angezeigt.

Hat jemand von euch ähnliche Erfahrungen gemacht oder eine Lösung für dieses Problem? Ich würde mich über eure Hilfe oder Ratschläge freuen, wie ich beide Wärmepumpen erfolgreich in Home Assistant integrieren kann.

Vielen Dank im Voraus für eure Unterstützung!

Beste Grüße,

![IMG_5358](https://github.com/signalkraft/mypyllant-component/assets/35847674/a1c457ba-650b-4a7a-a47c-0dbf7661b9f9)
![Screenshot 2023-11-27 131808](https://github.com/signalkraft/mypyllant-component/assets/35847674/060d68c6-e24c-4db2-ae44-f8ddfada0116)

**Comment by BB-78** [comment]
I have the same issue. A solution would be really nice!

**Comment by ml1nk** [comment]
I tried to fix #15 with #64 today and I think it shouldn't be too hard to differentiate between the two. Are you still interested in a fix and are willing to test it?

**Comment by andyx87** [comment]
Good Morning,
yes I'm still interested. I would be great.

**Comment by BB-78** [comment]
I am still interested and willing to test it.

**Comment by andyx87** [comment]
A sensors for the energy data and the heating energy efficiency of the overall system would be sufficient.

**Comment by BB-78** [comment]
> Sensors for the energy data and the heating energy efficiency of the overall system would be sufficient.

I second that.

**Comment by ml1nk** [comment]
How does it look with https://github.com/ml1nk/mypyllant-component.git? There will surely some changes (if it's working at all) until this is merged, see #64, but feedback is welcome.

Please note, that you need to remove the existing integration before testing.

**Comment by andyx87** [comment]
I unistalled the component from ha and reinstalled it over hacs, but for me, there are no changes. did i make something wrong?

**Comment by signalkraft** [comment]
@ml1nk I can also create a beta release from your PR, let me know when you think it's in a testable state.

**Comment by ml1nk** [comment]
@andyx87 Have you added my repository and installed it from there? You should at least see the names changed, even if it isn't working for you.

@signalkraft If it isn't too much work, that would be nice.

**Comment by signalkraft** [comment]
https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.0b0

Here's a pre-release with the changes that @ml1nk contributed! Feedback would be appreciated, but make sure to read the warning in the release notes.

**Comment by andyx87** [comment]
That’s with 0.7
![IMG_5790](https://github.com/signalkraft/mypyllant-component/assets/35847674/c0fa33b7-7292-4c72-838d-ad9310112b3e)

**Comment by ml1nk** [comment]
Thanks for testing. As it splits your aroTHERM and the hydraulic station the changes are somewhat working and it now shows all devices separately.

There are some possibilities i can think of why it isn't working as expected:
- The device_uuid isn't unique in this case and it overwrites the device/entities like before
- There is only one device with all the data of both heat pump
  - does the data looks like it is the sum of both or clearly one of them?
- The data isn't there at all (most probably)

If you provide some test data (https://github.com/signalkraft/myPyllant?tab=readme-ov-file#contributing-test-data) i will try to fix it.

@signalkraft Do you have more ideas?

**Comment by andyx87** [comment]
The aerotherm device shows only the energy data of one heat pump. It is not the sum of both.

**Comment by andyx87** [comment]
![IMG_5795](https://github.com/signalkraft/mypyllant-component/assets/35847674/37fcb0a8-23f2-458d-b1d6-3f9010e298cd)
![IMG_5796](https://github.com/signalkraft/mypyllant-component/assets/35847674/c22b281c-b3ec-4527-bc91-4aa0c67e2374)
![IMG_5797](https://github.com/signalkraft/mypyllant-component/assets/35847674/38b13a2b-741e-4461-94f4-43e7a5b0c2fc)
![IMG_5798](https://github.com/signalkraft/mypyllant-component/assets/35847674/96a5a50f-ffba-465e-8f25-75fa4010fd5c)
![IMG_5799](https://github.com/signalkraft/mypyllant-component/assets/35847674/298cb51e-e875-497d-84e3-c102faa71513)
![IMG_5800](https://github.com/signalkraft/mypyllant-component/assets/35847674/9b1c688b-5f8f-4ce3-aff7-519022c83028)
![IMG_5801](https://github.com/signalkraft/mypyllant-component/assets/35847674/8da0ef4e-b1eb-43d5-a2e1-4dd97f867522)

**Comment by signalkraft** [comment]
@ml1nk test data would probably help, I agree. Maybe the mapping of device data to entities is breaking with multiple systems.

**Comment by ml1nk** [comment]
Nether the library nor the component looks suspicious to me. The only thing left without test data is to manipulate my own by guessing how it could look from vaillants side, but i would rather use yours (@andyx87) :)

**Comment by andyx87** [comment]
Can I generate test data with HA OS?

**Comment by ml1nk** [comment]
Not that it is know how, but you can try to look up "/config/logs" and see if you see some errors from mypyllant when syncing.

**Comment by andyx87** [comment]
Vielleicht hilft das?

![Screenshot 2023-12-29 211138](https://github.com/signalkraft/mypyllant-component/assets/35847674/44fc8de0-ad70-4e17-8c2a-685951fbb951)

**Comment by signalkraft** [comment]
To help with this I added a new service `generate_test_data` in this release: https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.0b2

After install you can go to https://my.home-assistant.io/redirect/developer_services/ and select `mypyllant: generate_test_data`. Please post the output here. It's already anonymized, but please double check that no sensitive data is in there.

**Comment by ml1nk** [comment]
When i controlled my testdata i would expect, that the missing devices are somewhere in "secondary_heat_generators" which is an empty array in my system, which wouldn't be checked if i read models.py#L342-L350 correctly:
~~~
    @property
    def raw_devices(self) -> Iterator[tuple[str, dict]]:
        for key, device in self.current_system.items():
            if isinstance(device, dict) and "device_uuid" in device:
                dtc = self.diagnostic_trouble_codes_by_serial_number(
                    device["device_serial_number"]
                )
                device["diagnostic_trouble_codes"] = dtc
                yield key, device
~~~

There probably more auxiliary heat generators somewhere in the testdata of @andyx87 inside "secondary_heat_generators", so I''m excited how it looks like.

**Comment by andyx87** [comment]
homes:
  - homeName: d2daff4a69005f9639a0531648352f9a4f7fd57d
    serialNumber: 7181f45161f0efcf33aeafaf1c3c54f81ec4f450
    systemId: 7571042b8af21b829bda040425f77a76706b03d7
    productMetadata:
      productType: VR921
      productionYear: "23"
      productionWeek: "19"
      articleNumber: "0020260962"
    state: CLAIMED
    migrationState: FINISHED
    firmware:
      version: 0357.40.32
      updateEnabled: true
      updateRequired: false
    nomenclature: VR 921
    cag: false
    countryCode: DE
    productInformation: VR921
    firmwareVersion: 0357.40.32
7571042b8af21b829bda040425f77a76706b03d7:
  control_identifier:
    controlIdentifier: tli
  time_zone:
    timeZone: Europe/Berlin
  diagnostic_trouble_codes:
    - serialNumber: 7181f45161f0efcf33aeafaf1c3c54f81ec4f450
      articleNumber: "0020260962"
      codes: []
    - serialNumber: 6393da755ab2c3dc3bbae88ae6043a4ff06f9864
      articleNumber: "0010021118"
      codes: []
    - serialNumber: cac1a4f1cee23448eef68cc847022ca801a4a3b3
      articleNumber: "0020260914"
      codes: []
    - serialNumber: e4ae823e5c0721e8ae0abb6477fc0730bc522c73
      articleNumber: "0020184846"
      codes: []
    - serialNumber: 6393da755ab2c3dc3bbae88ae6043a4ff06f9864
      articleNumber: "0010021118"
      codes: []
    - serialNumber: b8ed8afd17ba811e9a6f6c90c628013685d91b4d
      articleNumber: "0010023609"
      codes: []
  connection_status:
    connected: true
  system:
    state:
      system:
        outdoorTemperature: 7.6914062
        systemFlowTemperature: 37.625
        systemWaterPressure: 1.5
        outdoorTemperatureAverage24h: 9.2109375
      zones:
        - index: 0
          desiredRoomTemperatureSetpointHeating: 21.5
          desiredRoomTemperatureSetpoint: 21.5
          currentRoomTemperature: 15.975
          currentRoomHumidity: 60
          currentSpecialFunction: NONE
          heatingState: HEATING_UP
      circuits:
        - index: 0
          circuitState: HEATING
          currentCircuitFlowTemperature: 36.8125
          heatingCircuitFlowSetpoint: 37.098827
          calculatedEnergyManagerState: HEATING_ACTIVE
      dhw:
        - index: 255
          currentSpecialFunction: REGULAR
          currentDhwTemperature: 46.5
    properties:
      system:
        controllerType: VRC720
        systemScheme: 8
        backupHeaterType: CONDENSING
        backupHeaterAllowedFor: DHW_AND_HEATING
        moduleConfigurationVR71: 3
        energyProvidePowerCutBehavior: DISABLE_HEATPUMP_AND_BACKUP_HEATER
      zones:
        - index: 0
          isActive: true
          zoneBinding: CENTRAL_CONTROL
          isCoolingAllowed: false
          associatedCircuitIndex: 0
      circuits:
        - index: 0
          mixerCircuitTypeExternal: HEATING
          heatingCircuitType: MIXER_CIRCUIT_EXTERNAL
          isCoolingAllowed: false
        - index: 1
          mixerCircuitTypeExternal: FIX_VALUE
          heatingCircuitType: DIRECT_HEATING_CIRCUIT
          isCoolingAllowed: false
        - index: 2
          mixerCircuitTypeExternal: FIX_VALUE
          heatingCircuitType: DIRECT_HEATING_CIRCUIT
          isCoolingAllowed: false
      dhw:
        - index: 255
          minSetpoint: 35
          maxSetpoint: 70
    configuration:
      system:
        continuousHeatingStartSetpoint: -26
        alternativePoint: -21
        heatingCircuitBivalencePoint: -5
        dhwBivalencePoint: -7
        automaticCoolingOnOff: false
        adaptiveHeatingCurve: false
        dhwMaximumLoadingTime: 90
        dhwHysteresis: 5
        dhwFlowSetpointOffset: 2
        continuousHeatingRoomSetpoint: 20
        hybridControlStrategy: BIVALENCE_POINT
        maxFlowSetpointHpError: 20
        dhwMaximumTemperature: 80
        maximumPreheatingTime: 0
        paralellTankLoadingAllowed: true
      zones:
        - index: 0
          general:
            name: Zuhause
          heating:
            operationModeHeating: TIME_CONTROLLED
            setBackTemperature: 17
            manualModeSetpointHeating: 21
            timeProgramHeating:
              metaInfo:
                minSlotsPerDay: 0
                maxSlotsPerDay: 12
                setpointRequiredPerSlot: true
              monday:
                - startTime: 0
                  endTime: 1440
                  setpoint: 21.5
              tuesday:
                - startTime: 0
                  endTime: 1440
                  setpoint: 21.5
              wednesday:
                - startTime: 0
                  endTime: 1440
                  setpoint: 21.5
              thursday:
                - startTime: 0
                  endTime: 1440
                  setpoint: 21.5
              friday:
                - startTime: 0
                  endTime: 1440
                  setpoint: 21.5
              saturday:
                - startTime: 0
                  endTime: 1440
                  setpoint: 21.5
              sunday:
                - startTime: 0
                  endTime: 1440
                  setpoint: 21.5
      circuits:
        - index: 0
          heatingCurve: 0.75000006
          heatingFlowTemperatureMinimumSetpoint: 20
          heatingFlowTemperatureMaximumSetpoint: 55
          heatDemandLimitedByOutsideTemperature: 20
          heatingCircuitFlowSetpointExcessOffset: 0
          coolingFlowTemperatureMinimumSetpoint: 20
          setBackModeEnabled: false
          roomTemperatureControlMode: NON
      dhw:
        - index: 255
          operationModeDhw: TIME_CONTROLLED
          tappingSetpoint: 50
          timeProgramDhw:
            metaInfo:
              minSlotsPerDay: 0
              maxSlotsPerDay: 3
              setpointRequiredPerSlot: false
            monday:
              - startTime: 120
                endTime: 360
              - startTime: 660
                endTime: 960
            tuesday:
              - startTime: 120
                endTime: 360
              - startTime: 660
                endTime: 960
            wednesday:
              - startTime: 120
                endTime: 360
              - startTime: 660
                endTime: 960
            thursday:
              - startTime: 120
                endTime: 360
              - startTime: 660
                endTime: 960
            friday:
              - startTime: 120
                endTime: 360
              - startTime: 660
                endTime: 960
            saturday:
              - startTime: 120
                endTime: 360
              - startTime: 660
                endTime: 960
            sunday:
              - startTime: 120
                endTime: 360
              - startTime: 660
                endTime: 960
          timeProgramCirculationPump:
            metaInfo:
              minSlotsPerDay: 0
              maxSlotsPerDay: 3
              setpointRequiredPerSlot: false
            monday:
              - startTime: 270
                endTime: 480
              - startTime: 600
                endTime: 900
              - startTime: 1080
                endTime: 1260
            tuesday:
              - startTime: 270
                endTime: 480
              - startTime: 600
                endTime: 900
              - startTime: 1080
                endTime: 1260
            wednesday:
              - startTime: 270
                endTime: 480
              - startTime: 600
                endTime: 900
              - startTime: 1080
                endTime: 1260
            thursday:
              - startTime: 270
                endTime: 480
              - startTime: 600
                endTime: 900
              - startTime: 1080
                endTime: 1260
            friday:
              - startTime: 270
                endTime: 480
              - startTime: 600
                endTime: 900
              - startTime: 1080
                endTime: 1260
            saturday:
              - startTime: 270
                endTime: 480
              - startTime: 600
                endTime: 900
              - startTime: 1080
                endTime: 1260
            sunday:
              - startTime: 270
                endTime: 480
              - startTime: 600
                endTime: 900
              - startTime: 1080
                endTime: 1260
  current_system:
    system_type: HEATPUMP_CASCADE
    has_emf_capable_devices: true
    primary_heat_generator:
      device_uuid: 4f334b0a6fb2b942f84ad28334cfd68b880a8a72
      ebus_id: HMU03
      spn: 351
      bus_coupler_address: 0
      article_number: "0010021118"
      emfValid: true
      device_serial_number: 2633e35b2e3ce9aa37d1d853fa61612efd5f3805
      device_type: HEATPUMP
      first_data: "2023-10-11T03:46:18Z"
      last_data: "2023-12-30T04:16:27Z"
      data:
        - operation_mode: DOMESTIC_HOT_WATER
          value_type: CONSUMED_ELECTRICAL_ENERGY
          calculated: false
          from: "2023-10-11T03:46:19Z"
          to: "2023-12-30T04:16:23Z"
        - operation_mode: HEATING
          value_type: CONSUMED_ELECTRICAL_ENERGY
          calculated: false
          from: "2023-10-11T03:46:18Z"
          to: "2023-12-30T04:16:23Z"
        - operation_mode: DOMESTIC_HOT_WATER
          value_type: EARNED_ENVIRONMENT_ENERGY
          calculated: false
          from: "2023-10-11T03:46:20Z"
          to: "2023-12-30T04:16:26Z"
        - operation_mode: HEATING
          value_type: EARNED_ENVIRONMENT_ENERGY
          calculated: false
          from: "2023-10-11T03:46:19Z"
          to: "2023-12-30T04:16:26Z"
        - operation_mode: HEATING
          value_type: HEAT_GENERATED
          calculated: true
          from: "2023-10-11T03:46:19Z"
          to: "2023-12-30T04:16:23Z"
        - operation_mode: DOMESTIC_HOT_WATER
          value_type: HEAT_GENERATED
          calculated: true
          from: "2023-10-11T03:46:20Z"
          to: "2023-12-30T04:16:23Z"
      product_name: aroTHERM plus
    secondary_heat_generators:
      - device_uuid: bc84fcd6f80d327bcc66f69a2a78a921eeca0959
        ebus_id: HMU03
        spn: 351
        bus_coupler_address: 24
        article_number: "0010021118"
        emfValid: true
        device_serial_number: 6393da755ab2c3dc3bbae88ae6043a4ff06f9864
        device_type: HEATPUMP
        first_data: "2023-10-11T03:46:25Z"
        last_data: "2023-12-30T04:16:38Z"
        data:
          - operation_mode: DOMESTIC_HOT_WATER
            value_type: CONSUMED_ELECTRICAL_ENERGY
            calculated: false
            from: "2023-10-11T03:46:25Z"
            to: "2023-12-30T04:16:34Z"
          - operation_mode: HEATING
            value_type: CONSUMED_ELECTRICAL_ENERGY
            calculated: false
            from: "2023-10-11T03:46:25Z"
            to: "2023-12-30T04:16:33Z"
          - operation_mode: DOMESTIC_HOT_WATER
            value_type: EARNED_ENVIRONMENT_ENERGY
            calculated: false
            from: "2023-10-11T03:46:26Z"
            to: "2023-12-30T04:16:36Z"
          - operation_mode: HEATING
            value_type: EARNED_ENVIRONMENT_ENERGY
            calculated: false
            from: "2023-10-11T03:46:26Z"
            to: "2023-12-30T04:16:35Z"
          - operation_mode: DOMESTIC_HOT_WATER
            value_type: HEAT_GENERATED
            calculated: false
            from: "2023-10-11T03:46:27Z"
            to: "2023-12-30T04:16:37Z"
          - operation_mode: HEATING
            value_type: HEAT_GENERATED
            calculated: false
            from: "2023-10-11T03:46:27Z"
            to: "2023-12-30T04:16:37Z"
        product_name: aroTHERM plus
    electric_backup_heater:
      device_uuid: 09594d943eb7923ed1f5b9d856856ce518ac924a
      ebus_id: VWZ02
      spn: 351
      bus_coupler_address: 0
      article_number: "0010023609"
      emfValid: true
      device_serial_number: b8ed8afd17ba811e9a6f6c90c628013685d91b4d
      device_type: ELECTRIC_AUXILIARY_HEATER
      first_data: "2023-10-11T03:46:22Z"
      last_data: "2023-12-30T04:16:30Z"
      data:
        - operation_mode: DOMESTIC_HOT_WATER
          value_type: CONSUMED_ELECTRICAL_ENERGY
          calculated: false
          from: "2023-10-11T03:46:23Z"
          to: "2023-12-30T04:16:30Z"
        - operation_mode: HEATING
          value_type: CONSUMED_ELECTRICAL_ENERGY
          calculated: false
          from: "2023-10-11T03:46:22Z"
          to: "2023-12-30T04:16:29Z"
        - operation_mode: DOMESTIC_HOT_WATER
          value_type: HEAT_GENERATED
          calculated: false
          from: "2023-10-11T03:46:23Z"
          to: "2023-12-30T04:16:30Z"
        - operation_mode: HEATING
          value_type: HEAT_GENERATED
          calculated: false
          from: "2023-10-11T03:46:23Z"
          to: "2023-12-30T04:16:30Z"
      product_name: hydraulic station
    solar_station: null
    ventilation: null
    gateway: null
  mpc:
    devices: []
  device_buckets:
    startDate: "2023-12-29T00:00:00Z"
    endDate: "2023-12-30T00:00:00Z"
    resolution: HOUR
    operationMode: DOMESTIC_HOT_WATER
    energyType: CONSUMED_ELECTRICAL_ENERGY
    totalConsumption: 5000
    data:
      - startDate: "2023-12-29T00:00:00Z"
        endDate: "2023-12-29T01:00:00Z"
        value: 726.9444444444445
      - startDate: "2023-12-29T01:00:00Z"
        endDate: "2023-12-29T02:00:00Z"
        value: 1000
      - startDate: "2023-12-29T02:00:00Z"
        endDate: "2023-12-29T03:00:00Z"
        value: 273.05555555555554
      - startDate: "2023-12-29T03:00:00Z"
        endDate: "2023-12-29T04:00:00Z"
        value: 0
      - startDate: "2023-12-29T04:00:00Z"
        endDate: "2023-12-29T05:00:00Z"
        value: 0
      - startDate: "2023-12-29T05:00:00Z"
        endDate: "2023-12-29T06:00:00Z"
        value: 0
      - startDate: "2023-12-29T06:00:00Z"
        endDate: "2023-12-29T07:00:00Z"
        value: 0
      - startDate: "2023-12-29T07:00:00Z"
        endDate: "2023-12-29T08:00:00Z"
        value: 0
      - startDate: "2023-12-29T08:00:00Z"
        endDate: "2023-12-29T09:00:00Z"
        value: 0
      - startDate: "2023-12-29T09:00:00Z"
        endDate: "2023-12-29T10:00:00Z"
        value: 726.9444444444445
      - startDate: "2023-12-29T10:00:00Z"
        endDate: "2023-12-29T11:00:00Z"
        value: 1726.9444444444443
      - startDate: "2023-12-29T11:00:00Z"
        endDate: "2023-12-29T12:00:00Z"
        value: 546.1111111111111
      - startDate: "2023-12-29T12:00:00Z"
        endDate: "2023-12-29T13:00:00Z"
        value: 0
      - startDate: "2023-12-29T13:00:00Z"
        endDate: "2023-12-29T14:00:00Z"
        value: 0
      - startDate: "2023-12-29T14:00:00Z"
        endDate: "2023-12-29T15:00:00Z"
        value: 0
      - startDate: "2023-12-29T15:00:00Z"
        endDate: "2023-12-29T16:00:00Z"
        value: 0
      - startDate: "2023-12-29T16:00:00Z"
        endDate: "2023-12-29T17:00:00Z"
        value: 0
      - startDate: "2023-12-29T17:00:00Z"
        endDate: "2023-12-29T18:00:00Z"
        value: 0
      - startDate: "2023-12-29T18:00:00Z"
        endDate: "2023-12-29T19:00:00Z"
        value: 0
      - startDate: "2023-12-29T19:00:00Z"
        endDate: "2023-12-29T20:00:00Z"
        value: 0
      - startDate: "2023-12-29T20:00:00Z"
        endDate: "2023-12-29T21:00:00Z"
        value: 0
      - startDate: "2023-12-29T21:00:00Z"
        endDate: "2023-12-29T22:00:00Z"
        value: 0
      - startDate: "2023-12-29T22:00:00Z"
        endDate: "2023-12-29T23:00:00Z"
        value: 0
      - startDate: "2023-12-29T23:00:00Z"
        endDate: "2023-12-30T00:00:00Z"
        value: 0

**Comment by andyx87** [comment]
Another feature that would be pretty good:
If you could switch the fixed heating circuits (in my case index 1 and index 2) on and off. I would submit an explanation later this afternoon. I'm at work first.

**Comment by andyx87** [comment]
Über die SG Ready / PV Ready Schnittstelle an der Steuerung der Wärmepumpe hat man die folgenden Optionen bei den Heizanforderungen:
Einschaltempfehlung: Der Pufferspeicher wird auf den Sollwert erhitzt, der vom Heizsystem benötigt wird um die gewünschte Raumtemperatur zu erreichen.
Zwangseinschaltung: Das System stellt in jedem Fall eine Heizanforderung und erhitzt den Pufferspeicher auf den Wert der in dem virtuellen fixen Heizkreislauf eingestellt ist, plus den Offset Wert. 

Der Vorteil, den virtuellen Festwertkreislauf ein und auszuschalten besteht darin, dass man bei diesem Kreislauf eine AT Temperatur einstellen kann. Somit würde die Heizung keine Anforderung stellen, wenn die Außentemperatur über dem eingestellten Wert liegt. Somit wäre es möglich die Speichertemperaturen bei Solarüberschuss oder einem günstigen Strompreis (ich nutze Tibber) zu erhöhen, ohne unnötige Heizanforderungen zu stellen. 

————————————————-

The SG Ready / PV Ready interface on the heat pump control gives you the following options for heating requirements:
Switch-on recommendation: The buffer tank is heated to the setpoint required by the heating system to achieve the desired room temperature.
Forced switch-on: The system always makes a heating request and heats the buffer tank to the value set in the virtual fixed heating circuit, plus the offset value.

The advantage of switching the virtual fixed value circuit on and off is that you can set an AT temperature for this circuit. This means that the heating would not make a request if the outside temperature is above the set value. This would make it possible to increase the storage temperatures when there is a solar surplus or a cheap electricity price (I use Tibber) without creating unnecessary heating requirements.

**Comment by ml1nk** [comment]
It seems my assumption could be correct, that 
~~~python
    @property
    def raw_devices(self) -> Iterator[tuple[str, dict]]:
        for key, device in self.current_system.items(): # merged with self.current_system.secondary_heat_generator.items()
            if isinstance(device, dict) and "device_uuid" in device:
                dtc = self.diagnostic_trouble_codes_by_serial_number(
                    device["device_serial_number"]
                )
                device["diagnostic_trouble_codes"] = dtc
                yield key, device
~~~
is ignoring "secondary_heat_generator" as it isn't a dict and just need to also loop through it like it does with self.current_system directly.

@signalkraft Are you already fixing this and adding the new test data or shall i do it?

@andyx87 Seems interesting, but please create another issue for this as I hope to get this issue closed after merging.

**Comment by signalkraft** [comment]
@ml1nk I've added test data, but I haven't encountered this issue. Feel free to update it!

**Comment by signalkraft** [comment]
Thanks to @ml1nk multiple heatpumps should work in the latest pre-release. Let us know, if it works for you @andyx87!

**Comment by andyx87** [comment]
Yes!
Its working. Thank you so much :-)

**Comment by signalkraft** [comment]
I tested the update on my system as well, everything seems fine so I'm closing this. Again, many thanks @ml1nk for your contribution!

**Comment by ml1nk** [comment]
@rmalbrecht Have you deleted the integration and added it again? What devices are duplicated?
