### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by snp-g** [signalkraft/mypyllant-component#56]
Hi

when I enter the myVaillant credentials

![image](https://github.com/signalkraft/mypyllant-component/assets/37530503/5acf3e3f-203a-4351-9e13-980659782f66)

I got this error

![image](https://github.com/signalkraft/mypyllant-component/assets/37530503/29d5b844-9bc6-4048-94d1-ab2f72d14a23)

Could you help me, please? 

myPyllant v0.6.1

**Comment by snp-g** [comment]
It seems there is a problem with http to https redirect

```
2023-11-28 20:55:11.578 DEBUG (MainThread) [myPyllant.api] Session expires in 2023-11-28 21:00:11.578532
2023-11-28 20:55:11.580 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://identity.vaillant-group.com/auth/realms/vaillant-czechrepublic-b2c/protocol/openid-connect/auth'), headers=<CIMultiDict()>)
2023-11-28 20:55:11.674 ERROR (MainThread) [custom_components.mypyllant.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mypyllant/config_flow.py", line 178, in async_step_user
    username = await validate_input(self.hass, user_input)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/config_flow.py", line 86, in validate_input
    await api.login()
  File "/config/deps/lib/python3.11/site-packages/myPyllant/api.py", line 159, in login
    async with self.aiohttp_session.get(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 624, in _request
```

**Comment by pdpelsem** [comment]
I have the same issue.

**Comment by snp-g** [comment]
I guess this is a full log, so I hope someone finds it useful in helping to troubleshoot it.

`2023-11-29 07:18:10.640 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://identity.vaillant-group.com/auth/realms/vaillant-czechrepublic-b2c/protocol/openid-connect/auth'), headers=<CIMultiDict()>)
2023-11-29 07:18:10.858 DEBUG (MainThread) [myPyllant.api] Got response <!DOCTYPE html>
<html class="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="robots" content="noindex, nofollow">

            <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <script>
  if (document.documentElement && document.documentElement.style && document.documentElement.style.setProperty) {
    document.documentElement.style.setProperty('--vh', '' + (window.innerHeight * 0.01) + 'px');
  }
</script><title>Přihlásit do Vaillant Česká republika</title>

  <link rel="apple-touch-icon" sizes="180x180" href="/auth/resources/6fr79/login/vaillant-czechrepublic-b2c/favicons/va/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/auth/resources/6fr79/login/vaillant-czechrepublic-b2c/favicons/va/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/auth/resources/6fr79/login/vaillant-czechrepublic-b2c/favicons/va/favicon-16x16.png">
  <link rel="manifest" href="/auth/resources/6fr79/login/vaillant-czechrepublic-b2c/favicons/va/site.webmanifest">
  <link rel="mask-icon" href="/auth/resources/6fr79/login/vaillant-czechrepublic-b2c/favicons/va/safari-pinned-tab.svg"
        color="#00917e">
  <link rel="shortcut icon" href="/auth/resources/6fr79/login/vaillant-czechrepublic-b2c/favicons/va/favicon.ico">
  <meta name="msapplication-TileColor" content="#00917e">
  <meta name="msapplication-config" content="/auth/resources/6fr79/login/vaillant-czechrepublic-b2c/favicons/va/browserconfig.xml">
  <meta name="theme-color" content="#ffffff">
            <link href="/auth/resources/6fr79/login/vaillant-czechrepublic-b2c/2632/css/login.css" rel="stylesheet" />
            <link href="/auth/resources/6fr79/login/vaillant-czechrepublic-b2c/2632/css/brand-vaillant-b2c.css" rel="stylesheet" />
            <script src="/auth/resources/6fr79/login/vaillant-czechrepublic-b2c/2632/js/login.js" type="text/javascript"></script>
</head>

<body class="vaillant-czechrepublic-b2c theme-b2c">
<div class="main-content">
    <div id="kc-header" class="">
        <div id="kc-header-wrapper"
             class="">Vaillant Česká republika</div>
    </div>
    <div class="main-box">
        <header class="">
                <h1 id="kc-page-title">        Přihlásit k vašemu účtu

</h1>
      </header>
      <div id="kc-content">
        <div id="kc-content-wrapper">


    <div id="kc-form">
      <div id="kc-form-wrapper">
            <form id="kc-form-login" onsubmit="login.disabled = true; return true;" action="https://identity.vaillant-group.com/auth/realms/vaillant-czechrepublic-b2c/login-actions/authenticate?session_code=token_removed&amp;execution=**token_removed**&amp;client_id=myvaillant&amp;tab_id=**token_removed**" method="post">
                    <div class="form-group">
                        <label for="username" class="">E-mail</label>

                        <input tabindex="1" id="username" placeholder="" class="" name="username" value="" type="email" autofocus autocomplete="off"
                               aria-invalid=""
                        />


                    </div>

                <div class="form-group">
                    <label for="password" class="">Heslo</label>

                    <input tabindex="2" id="password" placeholder="" class="" name="password" type="password" autocomplete="off"
                           aria-invalid=""
                    />


                </div>

                <div class="form-group form-settings">
                    <div id="kc-form-options">
                        </div>
                        <div class="form-options-wrapper">
                                <span><a tabindex="5" href="/auth/realms/vaillant-czechrepublic-b2c/login-actions/reset-credentials?client_id=myvaillant&amp;tab_id=token_removed">Obnovit heslo</a></span>
                        </div>

                  </div>

                  <div id="kc-form-buttons" class="form-group">
                      <input type="hidden" id="id-hidden-input" name="credentialId" />
                      <input tabindex="4" class="   " name="login" id="kc-login" type="submit" value="Přihlásit se"/>
                  </div>
            </form>
        </div>

    </div>





        </div>
      </div>

    </div>
  <div class="cookie-notice"><div>Soubor cookie nenalezen. Ujistěte se prosím, že máte v prohlížeči povolené cookies.</div></div>
  <footer>
    
      <ul>
        
          <li>
            <a href='https://myvaillant.com/vaillant-pp.html?lang=cs' target="_blank">Prohlášení o ochraně údajů</a>
          </li>
        
          <li>
            <a href='https://myvaillant.com/vaillant-tac.html?lang=cs' target="_blank">Podmínky používání</a>
          </li>
        
      </ul>
    
    <span class="support-id">Support ID: **9479026477f7e6e80997a9c1a6d70ba4**</span>
  </footer>
</div></body>
</html>

2023-11-29 07:18:10.858 DEBUG (MainThread) [myPyllant.api] Got login url https://identity.vaillant-group.com/auth/realms/vaillant-czechrepublic-b2c/login-actions/authenticate?session_code=**token_removed**&client_id=myvaillant&tab_id=**token_removed**
2023-11-29 07:18:10.858 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='POST', url=URL('https://identity.vaillant-group.com/auth/realms/vaillant-czechrepublic-b2c/login-actions/authenticate'), headers=<CIMultiDict()>)
2023-11-29 07:18:12.018 DEBUG (MainThread) [myPyllant.api] Got response 
2023-11-29 07:18:12.018 DEBUG (MainThread) [myPyllant.api] Got login response headers <CIMultiDictProxy('Date': 'Wed, 29 Nov 2023 06:18:10 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Set-Cookie': 'INGRESSCOOKIE=token_removed|token_removed; Path=/auth(?!/(admin|metrics|realms/master).*)/; HttpOnly', 'Referrer-Policy': 'no-referrer', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Robots-Tag': 'none', 'Cache-Control': 'no-store, must-revalidate, max-age=0', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "frame-src 'self'; frame-ancestors 'self'; object-src 'none';", 'Set-Cookie': 'KC_RESTART=; Version=1; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/vaillant-czechrepublic-b2c/; Secure; HttpOnly', 'Set-Cookie': 'KEYCLOAK_IDENTITY=**token_removed**; Version=1; Path=/auth/realms/vaillant-czechrepublic-b2c/; SameSite=None; Secure; HttpOnly', 'Set-Cookie': 'KEYCLOAK_IDENTITY_LEGACY=**token_removed**; Version=1; Path=/auth/realms/vaillant-czechrepublic-b2c/; Secure; HttpOnly', 'Set-Cookie': 'KEYCLOAK_SESSION=vaillant-czechrepublic-**token_removed**; Version=1; Expires=Wed, 29-Nov-2023 16:18:10 GMT; Max-Age=36000; Path=/auth/realms/vaillant-czechrepublic-b2c/; SameSite=None; Secure', 'Set-Cookie': 'KEYCLOAK_SESSION_LEGACY=vaillant-czechrepublic-**token_removed**; Version=1; Expires=Wed, 29-Nov-2023 16:18:10 GMT; Max-Age=36000; Path=/auth/realms/vaillant-czechrepublic-b2c/; Secure', 'Set-Cookie': 'KEYCLOAK_REMEMBER_ME=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/vaillant-czechrepublic-b2c/; Secure; HttpOnly', 'P3P': 'CP="This is not a P3P policy!"', 'X-XSS-Protection': '1; mode=block', 'Location': 'enduservaillant.page.link://login?session_state=**token_removed**&code=**token_removed**')>
2023-11-29 07:18:12.019 DEBUG (MainThread) [myPyllant.api] Got location from authorize endpoint: enduservaillant.page.link://login?session_state=**token_removed**&code=**token_removed**
2023-11-29 07:18:12.019 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='POST', url=URL('https://identity.vaillant-group.com/auth/realms/vaillant-czechrepublic-b2c/protocol/openid-connect/token'), headers=<CIMultiDict()>)
2023-11-29 07:18:12.171 DEBUG (MainThread) [myPyllant.api] Got response {"access_token":"**token_removed**","token_type":"Bearer","not-before-policy":0,"session_state":"**token_removed**","scope":"profile offline_access email"}
2023-11-29 07:18:12.171 DEBUG (MainThread) [myPyllant.api] Got session {'access_token': '**token_removed**', 'expires_in': 300, 'refresh_expires_in': 0, 'refresh_token': '**token_removed**', 'token_type': 'Bearer', 'not-before-policy': 0, 'session_state': '**token_removed**', 'scope': 'profile offline_access email'}
2023-11-29 07:18:12.171 DEBUG (MainThread) [myPyllant.api] Session expires in 2023-11-29 07:23:12.171493
2023-11-29 07:18:12.175 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://identity.vaillant-group.com/auth/realms/vaillant-czechrepublic-b2c/protocol/openid-connect/auth'), headers=<CIMultiDict()>)
2023-11-29 07:18:12.326 ERROR (MainThread) [custom_components.mypyllant.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mypyllant/config_flow.py", line 178, in async_step_user
    username = await validate_input(self.hass, user_input)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/config_flow.py", line 86, in validate_input
    await api.login()
  File "/config/deps/lib/python3.11/site-packages/myPyllant/api.py", line 159, in login
    async with self.aiohttp_session.get(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 624, in _request
    raise ValueError("Can redirect only to http or https")
ValueError: Can redirect only to http or https`

**Comment by hatage** [comment]
I have the same issue.

**Comment by signalkraft** [comment]
Could you please test if everything works in v0.6.0? That would help narrow it down.

**Comment by snp-g** [comment]
Hi Signalkraft

thank you for your support. I tried and it works. It found 5 devices.

![image](https://github.com/signalkraft/mypyllant-component/assets/37530503/eb668939-f4a0-4675-85a3-522f3feb8c4b)

If you want to troubleshoot v6.1 still please let me know.

**Comment by misterdeer** [comment]
Same problem with v0.6.1 here. Went back to v0.6.0 and it works.

**Comment by fellek** [comment]
> Could you please test if everything works in v0.6.0? That would help narrow it down.
Did not test 0.6.0, but downgrade to 0.5.5b worked for me. Upgrade to 0.6.1 worked also, after successfull login.

**Comment by misterdeer** [comment]
> > Could you please test if everything works in v0.6.0? That would help narrow it down.
> > Did not test 0.6.0, but downgrade to 0.5.5b worked for me. Upgrade to 0.6.1 worked also, after successfull login.

Yes, v0.6.0 works.

**Comment by misterdeer** [comment]
> Hi, initial configuration with v0.6.1 didn't work. Downgrading to v0.6.0 allowed me to add the integration. After that upgrade to v0.6.1 worked and the integration is still working.

For me v0.6.1 did not work anymore after restart. I'm still back on v0.6.0.

**Comment by misterdeer** [comment]
> This should be fixed in https://github.com/signalkraft/mypyllant-component/releases/tag/v0.6.2

Great, it works! Many thanks!

**Comment by mariandodu** [comment]
This error originated from a custom integration.

Logger: custom_components.mypyllant.config_flow
Source: custom_components/mypyllant/config_flow.py:180
Integration: myVAILLANT (documentation, issues)
First occurred: 15:27:05 (1 occurrences)
Last logged: 15:27:05

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mypyllant/config_flow.py", line 180, in async_step_user
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1597, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured

**Comment by Technikie** [comment]
Hello, i've got exactly the same ( In Dutch) as mariandodu: 

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.mypyllant.config_flow
Source: custom_components/mypyllant/config_flow.py:180
Integration: myVAILLANT (documentation, issues)
First occurred: 21:21:29 (1 occurrences)
Last logged: 21:21:29

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mypyllant/config_flow.py", line 180, in async_step_user
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1597, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured

**Comment by signalkraft** [comment]
Could you test with the latest release and let me know if this persists? Also, does this error affect the functionality at all? Or does everything work despite the error?

**Comment by snp-g** [comment]
HI,

thank you, however did not help, still an Unexpected Error came.

`2024-01-01 09:14:36.257 ERROR (MainThread) [custom_components.mypyllant.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mypyllant/config_flow.py", line 179, in async_step_user
    await self.async_set_unique_id(username)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1614, in async_set_unique_id
    raise data_entry_flow.AbortFlow("already_in_progress")
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_in_progress`

**Comment by signalkraft** [comment]
I looked at the code again, that should only happen if you've previously configured the integration with the same username. Is that the case? Can you maybe delete it and try again if it is?

**Comment by snp-g** [comment]
Hi,

firstly, I tried to connect over the existing configuration and I realized there could be a kind of issue so I deleted the configuration.

![image](https://github.com/signalkraft/mypyllant-component/assets/37530503/e9a0d226-2b60-4069-9c0d-41aaa3830ffe)

Then I tried to initiate it without configuration and logs are after I did it. I do not know if that is enough or do I need to do anything more.

**Comment by mariandodu** [comment]
Hello! I still can't use the integration! I tried a thousand times to reinstall!! Even if I succeed, at the first restart everything disappears! I only see "No devices or entities"! However, if I go to the Developer tool and give services "myVAILLANT: Generate Test Data" data appears!!homes:  - homeName: 00e8b403e3af809c2ec2aa7012bba544b3ebb79b    serialNumber: dfaae875bb38e5aa0f64d0bf4c8655e4cd74fab5    systemId: fb485db081728b63bf9edaa18fdff2782505ee9a    productMetadata:      productType: VR921      productionYear: "21"      productionWeek: "29"      articleNumber: "0020260964"    state: CLAIMED    migrationState: FINISHED    onlineState: ONLINE    firmware:      version: 0357.40.33      updateEnabled: true      updateRequired: false    nomenclature: VR 921    cag: false    countryCode: RO    productInformation: VR921    firmwareVersion: 0357.40.33fb485db081728b63bf9edaa18fdff2782505ee9a:  control_identifier:    controlIdentifier: tli  time_zone:    timeZone: Asia/Dubai  diagnostic_trouble_codes:    - serialNumber: 419c91567a9162e7ffa7bb60c47a082c6986de52      articleNumber: "0020262191"      codes: []    - serialNumber: 798cb3c32cf26f955235a359c6f80ee0a8d602f3      articleNumber: "0010024601"      codes: []    - serialNumber: dfaae875bb38e5aa0f64d0bf4c8655e4cd74fab5      articleNumber: "0020260964"      codes: []  connection_status:    connected: true  system:    state:      system:        outdoorTemperature: 2.25        systemWaterPressure: 1.6        outdoorTemperatureAverage24h: 0      zones:        - index: 0          desiredRoomTemperatureSetpointHeating: 20          desiredRoomTemperatureSetpoint: 20          currentRoomTemperature: 20.1875          currentSpecialFunction: NONE          heatingState: IDLE      circuits:        - index: 0          circuitState: HEATING          currentCircuitFlowTemperature: 61          heatingCircuitFlowSetpoint: 47.017685          calculatedEnergyManagerState: HEATING_ACTIVE      dhw:        - index: 255          currentSpecialFunction: REGULAR          currentDhwTemperature: 49.5    properties:      system:        controllerType: VRT380        systemScheme: 1        backupHeaterType: CONDENSING        backupHeaterAllowedFor: DHW_AND_HEATING        moduleConfigurationVR71: 3        energyProvidePowerCutBehavior: DISABLE_HEATPUMP_AND_BACKUP_HEATER      zones:        - index: 0          isActive: true          zoneBinding: CENTRAL_CONTROL          isCoolingAllowed: false          associatedCircuitIndex: 0      circuits:        - index: 0          mixerCircuitTypeExternal: HEATING          heatingCircuitType: DIRECT_HEATING_CIRCUIT          isCoolingAllowed: false      dhw:        - index: 255          minSetpoint: 35          maxSetpoint: 70    configuration:      system:        continuousHeatingStartSetpoint: -26        alternativePoint: -21        heatingCircuitBivalencePoint: 0        dhwBivalencePoint: -7        automaticCoolingOnOff: false        adaptiveHeatingCurve: false        dhwMaximumLoadingTime: 60        dhwHysteresis: 5        dhwFlowSetpointOffset: 25        continuousHeatingRoomSetpoint: 20        hybridControlStrategy: TRIVAI        maxFlowSetpointHpError: 25        dhwMaximumTemperature: 80        maximumPreheatingTime: 0        paralellTankLoadingAllowed: false      zones:        - index: 0          general:            name: Zone 1            holidayStartDateTime: "2019-01-01T00:00:00Z"            holidayEndDateTime: "2019-01-01T00:00:00Z"          heating:            operationModeHeating: MANUAL            setBackTemperature: 25            manualModeSetpointHeating: 20            timeProgramHeating:              metaInfo:                minSlotsPerDay: 0                maxSlotsPerDay: 12                setpointRequiredPerSlot: true              monday:                - startTime: 360                  endTime: 540                  setpoint: 21                - startTime: 1080                  endTime: 1260                  setpoint: 21              tuesday:                - startTime: 360                  endTime: 540                  setpoint: 21                - startTime: 1080                  endTime: 1260                  setpoint: 21              wednesday:                - startTime: 360                  endTime: 540                  setpoint: 21                - startTime: 1080                  endTime: 1260                  setpoint: 21              thursday:                - startTime: 360                  endTime: 540                  setpoint: 21                - startTime: 1080                  endTime: 1260                  setpoint: 21              friday:                - startTime: 360                  endTime: 540                  setpoint: 21                - startTime: 1080                  endTime: 1260                  setpoint: 21              saturday:                - startTime: 480                  endTime: 660                  setpoint: 21              sunday:                - startTime: 480                  endTime: 660                  setpoint: 21      circuits:        - index: 0          heatingCurve: 1.2          heatingFlowTemperatureMinimumSetpoint: 15          heatingFlowTemperatureMaximumSetpoint: 90          heatDemandLimitedByOutsideTemperature: 21          heatingCircuitFlowSetpointExcessOffset: 0          coolingFlowTemperatureMinimumSetpoint: 20          setBackModeEnabled: false          roomTemperatureControlMode: NON      dhw:        - index: 255          operationModeDhw: MANUAL          tappingSetpoint: 50          holidayStartDateTime: "2019-01-01T00:00:00Z"          holidayEndDateTime: "2019-01-01T00:00:00Z"          timeProgramDhw:            metaInfo:              minSlotsPerDay: 0              maxSlotsPerDay: 3              setpointRequiredPerSlot: false            monday:              - startTime: 360                endTime: 540              - startTime: 1080                endTime: 1260            tuesday:              - startTime: 360                endTime: 540              - startTime: 1080                endTime: 1260            wednesday:              - startTime: 360                endTime: 540              - startTime: 1080                endTime: 1260            thursday:              - startTime: 360                endTime: 540              - startTime: 1080                endTime: 1260            friday:              - startTime: 360                endTime: 540              - startTime: 1080                endTime: 1260            saturday:              - startTime: 480                endTime: 660            sunday:              - startTime: 480                endTime: 660          timeProgramCirculationPump:            metaInfo:              minSlotsPerDay: 0              maxSlotsPerDay: 3              setpointRequiredPerSlot: false            monday:              - startTime: 360                endTime: 540              - startTime: 1080                endTime: 1260            tuesday:              - startTime: 360                endTime: 540              - startTime: 1080                endTime: 1260            wednesday:              - startTime: 360                endTime: 540              - startTime: 1080                endTime: 1260            thursday:              - startTime: 360                endTime: 540              - startTime: 1080                endTime: 1260            friday:              - startTime: 360                endTime: 540              - startTime: 1080                endTime: 1260            saturday:              - startTime: 480                endTime: 660            sunday:              - startTime: 480                endTime: 660  current_system:    system_type: BOILER_OR_ELECTRIC_HEATER    has_emf_capable_devices: true    primary_heat_generator:      device_uuid: b0d3caa5a33bbf447a6a801e34b6d890621021ac      ebus_id: BAI00      spn: 376      bus_coupler_address: 0      article_number: "0010024601"      emfValid: true      device_serial_number: 798cb3c32cf26f955235a359c6f80ee0a8d602f3      device_type: BOILER      first_data: "2020-02-23T23:20:49Z"      last_data: "2024-02-24T01:06:54Z"      data:        - operation_mode: DOMESTIC_HOT_WATER          value_type: CONSUMED_ELECTRICAL_ENERGY          calculated: false          from: "2020-02-23T23:20:49Z"          to: "2024-02-24T01:06:54Z"        - operation_mode: HEATING          value_type: CONSUMED_ELECTRICAL_ENERGY          calculated: false          from: "2020-02-23T23:20:49Z"          to: "2024-02-24T01:06:54Z"        - operation_mode: DOMESTIC_HOT_WATER          value_type: CONSUMED_PRIMARY_ENERGY          calculated: false          from: "2020-02-23T23:20:49Z"          to: "2024-02-24T01:06:54Z"        - operation_mode: HEATING          value_type: CONSUMED_PRIMARY_ENERGY          calculated: false          from: "2020-02-23T23:20:49Z"          to: "2024-02-24T01:06:53Z"      product_name: VU 30CS/1-5 (N-INT2) ecoTEC plus    secondary_heat_generators: []    electric_backup_heater: null    solar_station: null    ventilation: null    gateway: null  mpc:    devices: []  rts:    statistics: []  device_buckets:    startDate: "2024-02-23T00:00:00Z"    endDate: "2024-02-24T00:00:00Z"    resolution: HOUR    operationMode: DOMESTIC_HOT_WATER    energyType: CONSUMED_ELECTRICAL_ENERGY    totalConsumption: 348.58799551524726    data:      - startDate: "2024-02-23T00:00:00Z"        endDate: "2024-02-23T01:00:00Z"        value: 11.87369864024729      - startDate: "2024-02-23T01:00:00Z"        endDate: "2024-02-23T02:00:00Z"        value: 11.940000000000001      - startDate: "2024-02-23T02:00:00Z"        endDate: "2024-02-23T03:00:00Z"        value: 12.162343750000002      - startDate: "2024-02-23T03:00:00Z"        endDate: "2024-02-23T04:00:00Z"        value: 22.931953125      - startDate: "2024-02-23T04:00:00Z"        endDate: "2024-02-23T05:00:00Z"        value: 13.694296875      - startDate: "2024-02-23T05:00:00Z"        endDate: "2024-02-23T06:00:00Z"        value: 10.90203125      - startDate: "2024-02-23T06:00:00Z"        endDate: "2024-02-23T07:00:00Z"        value: 15.613906249999998      - startDate: "2024-02-23T07:00:00Z"        endDate: "2024-02-23T08:00:00Z"        value: 12.447265625      - startDate: "2024-02-23T08:00:00Z"        endDate: "2024-02-23T09:00:00Z"        value: 23.637890625      - startDate: "2024-02-23T09:00:00Z"        endDate: "2024-02-23T10:00:00Z"        value: 14.107578125      - startDate: "2024-02-23T10:00:00Z"        endDate: "2024-02-23T11:00:00Z"        value: 12.364626427554846      - startDate: "2024-02-23T11:00:00Z"        endDate: "2024-02-23T12:00:00Z"        value: 12.040380757600753      - startDate: "2024-02-23T12:00:00Z"        endDate: "2024-02-23T13:00:00Z"        value: 11.115383439844402      - startDate: "2024-02-23T13:00:00Z"        endDate: "2024-02-23T14:00:00Z"        value: 11.152109375      - startDate: "2024-02-23T14:00:00Z"        endDate: "2024-02-23T15:00:00Z"        value: 21.0728125      - startDate: "2024-02-23T15:00:00Z"        endDate: "2024-02-23T16:00:00Z"        value: 13.216027514058595      - startDate: "2024-02-23T16:00:00Z"        endDate: "2024-02-23T17:00:00Z"        value: 13.112377229446546      - startDate: "2024-02-23T17:00:00Z"        endDate: "2024-02-23T18:00:00Z"        value: 15.214017131494861      - startDate: "2024-02-23T18:00:00Z"        endDate: "2024-02-23T19:00:00Z"        value: 18.815156249999998      - startDate: "2024-02-23T19:00:00Z"        endDate: "2024-02-23T20:00:00Z"        value: 21.503984375      - startDate: "2024-02-23T20:00:00Z"        endDate: "2024-02-23T21:00:00Z"        value: 15.809296875000001      - startDate: "2024-02-23T21:00:00Z"        endDate: "2024-02-23T22:00:00Z"        value: 11.643359375      - startDate: "2024-02-23T22:00:00Z"        endDate: "2024-02-23T23:00:00Z"        value: 11.133984375      - startDate: "2024-02-23T23:00:00Z"        endDate: "2024-02-24T00:00:00Z"        value: 11.083515625Trimis de pe iPad‑ul meuPe 23 feb. 2024, la 23:22, signalkraft ***@***.***> a scris:﻿
Are you still facing this issue?

**Comment by mariandodu** [comment]
This error originated from a custom integration.Logger: custom_components.mypyllantSource: helpers/update_coordinator.py:313Integration: myVAILLANT (documentation, issues)First occurred: 5:21:43 AM (2 occurrences)Last logged: 5:21:43 AMUnexpected error fetching myVAILLANT data: 'types.UnionType' object has no attribute '__origin__'Traceback (most recent call last):  File "/usr/local/lib/python3.12/site-packages/dacite/types.py", line 22, in extract_origin_collection    return collection.__extra__           ^^^^^^^^^^^^^^^^^^^^AttributeError: 'types.UnionType' object has no attribute '__extra__'. Did you mean: '__str__'?During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh    self.data = await self._async_update_data()                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/config/custom_components/mypyllant/__init__.py", line 350, in _async_update_data    data = [           ^  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 327, in get_systems    async for home in homes:  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 301, in get_homes    yield Home.from_api(timezone=timezone, **home_json)          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 69, in from_api    return from_dict(           ^^^^^^^^^^  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 64, in from_dict    value = _build_value(type_=field_type, data=field_data, config=config)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 101, in _build_value    if is_subclass(type_, cast_type):       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.12/site-packages/dacite/types.py", line 168, in is_subclass    if is_generic_collection(sub_type):       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.12/site-packages/dacite/types.py", line 147, in is_generic_collection    origin = extract_origin_collection(type_)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.12/site-packages/dacite/types.py", line 24, in extract_origin_collection    return collection.__origin__           ^^^^^^^^^^^^^^^^^^^^^AttributeError: 'types.UnionType' object has no attribute '__origin__'Trimis de pe iPad‑ul meuPe 23 feb. 2024, la 23:22, signalkraft ***@***.***> a scris:﻿
Are you still facing this issue?

**Comment by signalkraft** [comment]
Check https://github.com/signalkraft/mypyllant-component/issues/54 please
