### ISSUE TITLE
Stopped working after update to 2023.12.0

### ISSUE THREAD

**Issue by mgmtotorsperformance** [signalkraft/mypyllant-component#59]
### Before submitting a new issue

Wont load after update to 2023.12.0 

### Problem description

not working

### Logs

Logger: homeassistant.util.package
Source: util/package.py:102
First occurred: 20:40:26 (3 occurrences)
Last logged: 20:40:32

Unable to install package myPyllant==0.6.3: ERROR: Cannot install mypyllant==0.6.3 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Put your debug logs here
Be careful not to include tokens, emails, and other personal information
```

**Comment by JonSilver** [comment]
same here

**Comment by flobo1990** [comment]
+1

**Comment by alexgut72** [comment]
Same problem.

**Comment by miho9** [comment]
same problem here. I am still on 0.6.0.

**Comment by BB-78** [comment]
I have the same problem.

**Comment by CommanderROR9** [comment]
Yes, unfortunately same issue for me

**Comment by mirceadb7** [comment]
Same here

**Comment by andabac** [comment]
Same

**Comment by szflo** [comment]
+1

**Comment by edudele** [comment]
+1

**Comment by dcw77** [comment]
Same issue here 👍

**Comment by Gio-dot** [comment]
![image](https://github.com/signalkraft/mypyllant-component/assets/55327160/b3463b1b-f9f1-4bc5-bf81-4d8ae66a2fec)

**Comment by hoehm79** [comment]
+1

**Comment by nukleuz80** [comment]
Here the same...

**Comment by MichaelLachmann** [comment]
+1

**Comment by mathisschmieder** [comment]
+1

**Comment by matejsalamon** [comment]
The same issue...

**Comment by Technikie** [comment]
Here the same ;-(

**Comment by signalkraft** [comment]
This should be fixed in https://github.com/signalkraft/mypyllant-component/releases/tag/v0.6.2

**Comment by stomko11** [comment]
I can confirm it works for me

**Comment by misterdeer** [comment]
v0.6.2 works for me too. Many thanks!

**Comment by matejsalamon** [comment]
Thanks, it works for me as well

**Comment by mgmtotorsperformance** [comment]
Problem solved after update to v0.6.2
thanks

**Comment by habeas2023** [comment]
Thank you very much for your fast help! You will get a cup of coffee ;-)

**Comment by nukleuz80** [comment]
Perfect!

**Comment by habeas2023** [comment]
äh, sorry für meine Blindheit, aber ich finde keine Möglichkeit der Kaffeespende. Für einen kleinen Tipp wäre ich deshalb dankbar :-)
