### ISSUE TITLE
[myPyllant.api] Could not get diagnostic trouble codes

### ISSUE THREAD

**Issue by koejok** [signalkraft/mypyllant-component#62]
### Before submitting a new issue

- [ x] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [ x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Hi, I get a error code or hint or notice, how ever, many times a day in the Home Assistant core logs respectively in the host system logs from myVAILLANT integration.
Nevertheless Integration is working very well. 
Thank you for your work. How or where I can donate your work or spend a coffee? 

### Logs

```
Could not get diagnostic trouble codes

Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 832, in get_diagnostic_trouble_codes
response = await self.aiohttp_session.get(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 689, in _request
    resp.raise_for_status()
File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1059, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/********-****-****-****-************/diagnostic-trouble-codes')

```

**Comment by signalkraft** [comment]
It seems this endpoint sometimes becomes unavailable, but the log entry is only a warning and shouldn't affect anything. I guess you're not seeing this very often?

Thanks for the coffee offer, I currently don't have anything set up for that. I'll post a link in one of the release notes, when I get around to it!
