### ISSUE TITLE
Missing temperature values

### ISSUE THREAD

**Issue by ml1nk** [signalkraft/mypyllant-component#66]
### Before submitting a new issue

- [x] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Current the systemFlowTemperature (Tank Temperature) is shown, but one of my homes hasn't this value but instead:
~~~
        cylinderTemperatureSensorBottomDHW: 41.25
        cylinderTemperatureSensorTopCH: 38.75
        cylinderTemperatureSensorTopDHW: 50.4375
~~~

I would like to add these temperatures too and move systemFlowTemperature to the system entity instead the dhw entity without changing the controls in DHW which uses both values. In addition i would like add currentDhwTemperature to dhw, if exists.

Does someone know what the CH in cylinderTemperatureSensorTopCH means? Is it equivalent to systemFlowTemperature?

@signalkraft I would like create a pull request i the coming days, if you are happy with the changes.

### Logs

Already commited to myPyllant/tests/two_systems.

**Comment by signalkraft** [comment]
Sounds good, I've not seen the `CH` value before.

**Comment by Shackmeister** [comment]
@ml1nk 
Really hoping this can make it's way in, since I need it as well :)
Can you also add BottomCH?

Also
CH = Central Heating

**Comment by signalkraft** [comment]
Please try https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.3b8 and let me know if it shows these values for you

**Comment by ml1nk** [comment]
I wanted to work on it, after my other change is finally merged. Lucky me, this is no longer necessary. Works like a charm. Thanks @signalkraft :+1: 

![image](https://github.com/signalkraft/mypyllant-component/assets/4943440/46a8b1ea-5577-4331-af6d-8a135e313d27)

**Comment by Shackmeister** [comment]
@signalkraft any chance the Sysflow temperature sensor could be added as well? :)
