### ISSUE TITLE
Please report energy in kWh

### ISSUE THREAD

**Issue by Gio-dot** [signalkraft/mypyllant-component#71]
### Before submitting a new issue

- [x] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description
All energy values are currently in Wh. It would be much better to use kWh instead, so great and unintuitive numbers would be avoided. Do you think it would be possible to use kWh? 

### Logs

```
Put your debug logs here
Be careful not to include tokens, emails, and other personal information
```

**Comment by signalkraft** [comment]
You can pick your own units by clicking on the energy sensor, then settings, and selecting `kWh` in unit of measurement.
