### ISSUE TITLE
Deprecated constant which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by heinemannj** [signalkraft/mypyllant-component#72]
`ENERGY_WATT_HOUR was used from mypyllant, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.WATT_HOUR instead, please create a bug report at https://github.com/signalkraft/mypyllant-component/issues`

`PRESSURE_BAR was used from mypyllant, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.BAR instead, please create a bug report at https://github.com/signalkraft/mypyllant-component/issues`

`TEMP_CELSIUS was used from mypyllant, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/signalkraft/mypyllant-component/issues`

**Comment by ml1nk** [comment]
Nice catch. I will fix this.
