### ISSUE TITLE
Takten ermitteln

### ISSUE THREAD

**Issue by dominikruffing** [signalkraft/mypyllant-component#80]
Hallo,

ist es irgendwie möglich, dass Takten der Wärmepumpe zu ermitteln? Mir fehlt für eine entsprechende Statistik in HA die Current Power, die die API wohl nicht zur Verfügung stellt.

Gibt es ggf. einen Workaround dazu?

**Comment by signalkraft** [comment]
Fixed in https://github.com/signalkraft/mypyllant-component/issues/87 - I'll close this as a duplicate
