### ISSUE TITLE
Country (Turkey)

### ISSUE THREAD

**Issue by onurchaner** [signalkraft/mypyllant-component#84]
"Turkey country is missing. Can you add it?"

**Comment by signalkraft** [comment]
When you log into the app, it should open a website where you enter email / password. Can you copy that URL and post it here? Please remove any tokens, emails, etc. - I'm just interested in the part that looks like `realms/vaillant-germany-b2c`

**Comment by signalkraft** [comment]
Nevermind, figured it out. Will be in the next release.

**Comment by onurchaner** [comment]
Hi

realms/vaillant-turkiye-b2c

Thank you.

**Comment by signalkraft** [comment]
Can you test [the latest pre-release](https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.2b0) please and let me know if it works? You need to enable beta versions in HACS to see it.

**Comment by onurchaner** [comment]
Yes ! Its work. Thank You 🥰

**Comment by signalkraft** [comment]
No problem, glad it works!
