### ISSUE TITLE
Myvaillant not connecting to Aroterm plus

### ISSUE THREAD

**Issue by StefanM60** [signalkraft/mypyllant-component#9]
Hi, 
I know my case is not an issue here, but perhaps anybody can help.
i tried to connect my vr921 Gateway from sensoapp to myvaillant. Did not work incompatible so far.
So i bought a new gateway which i could register in the myvaillant app. Trying to connect to the Arotherm Plus system runs 
Into a timeout. Thats it, I tried a couple of times, always with this result. Does anybody use this combination in Germany ?
Any help is welcome:-). Thanks a lot

**Comment by signalkraft** [comment]
@StefanM60 sorry, I can't help with that. I have a similar setup, which connects fine.

Maybe try asking in https://www.haustechnikdialog.de/Forum/30/Waermepumpen or contacting Vaillant's support.
