### ISSUE TITLE
MyVaillant with VR700 - Missing entities for Energy Consumption and Yield

### ISSUE THREAD

**Issue by airthusiast** [signalkraft/mypyllant-component#97]
### Before submitting a new issue

- [x] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

After migrating VR700 from old Multimatic to MyVaillant, energy related entities are missing:

- Environment Yield
- Consumed Energy

Those entities were available in the Multimatic Integration (by @thomasgermain)
Checking the logs, we can see that it tries to reach a missing API endpoint (HTTP 404). Could this be related?

Currently using the latest Beta v0.7.3b3

### Logs

```
Error fetching myVAILLANT data: 404, message='Resource Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/vrc700/v1/emf/v2/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/devices/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/buckets?resolution=DAY&operationMode=DOMESTIC_HOT_WATER&energyType=CONSUMED_ELECTRICAL_ENERGY&startDate=2024-02-10T00:00:00Z&endDate=2024-02-11T00:00:00Z')
```

**Comment by signalkraft** [comment]
https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.3b4 should fix things

**Comment by switschel** [comment]
Works perfectly for me now, thx!

**Comment by airthusiast** [comment]
Same here, thanks @signalkraft !
